#!/bin/tcsh

wb_cmd_run -class-create-enum AnnotationSizingHandleTypeEnum  11 true \
   ANNOTATION_SIZING_HANDLE_BOX_BOTTOM   \
   ANNOTATION_SIZING_HANDLE_BOX_BOTTOM_LEFT   \
   ANNOTATION_SIZING_HANDLE_BOX_BOTTOM_RIGHT  \
   ANNOTATION_SIZING_HANDLE_BOX_LEFT  \
   ANNOTATION_SIZING_HANDLE_BOX_RIGHT  \
   ANNOTATION_SIZING_HANDLE_BOX_TOP  \
   ANNOTATION_SIZING_HANDLE_BOX_TOP_LEFT  \
   ANNOTATION_SIZING_HANDLE_BOX_TOP_RIGHT  \
   ANNOTATION_SIZING_HANDLE_ROTATION  \
   ANNOTATION_SIZING_HANDLE_LINE_END  \
   ANNOTATION_SIZING_HANDLE_LINE_START

