
/*LICENSE_START*/
/*
 *  Copyright (C) 2026 Washington University School of Medicine
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */
/*LICENSE_END*/

#define __NEUROGLANCER_ANNOTATION_FILE_IMPORTER_DECLARE__
#include "NeuroglancerAnnotationFileImporter.h"
#undef __NEUROGLANCER_ANNOTATION_FILE_IMPORTER_DECLARE__

#include <cmath>
#include <cstdint>

#include <QDataStream>
#include <QDir>
#include <QFile>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonValue>
#include <QStandardItemModel>

#include "AStringNaturalComparison.h"
#include "CaretAssert.h"
#include "CaretLogger.h"
#include "DataCompressZLib.h"
#include "DataFileException.h"
#include "DataFileContentInformation.h"
#include "FeatureFile.h"
#include "FileInformation.h"
#include "FeatureItem.h"
#include "FeatureItemGroup.h"
#include "FeatureLabel.h"
#include "FeatureLabelModel.h"
#include "FeatureItemModel.h"
#include "FeaturePropertyValue.h"
#include "QtFileHelper.h"

using namespace caret;


    
/**
 * \class caret::NeuroglancerAnnotationFileImporter 
 * \brief Neuroglancer pins file
 * \ingroup Files
 *
 * https://github.com/google/neuroglancer/blob/master/src/datasource/precomputed/annotations.md
 *
 * JSON reading code initially generated by Claude.
 */

/**
 * Constructor.
 * @param featureFile
 *    Data is imported into this feature file
 */
NeuroglancerAnnotationFileImporter::NeuroglancerAnnotationFileImporter(FeatureFile* featureFile)
: DataFile(),
m_featureFile(featureFile)
{
}

/**
 * Destructor.
 */
NeuroglancerAnnotationFileImporter::~NeuroglancerAnnotationFileImporter()
{
}

/**
 * @return True if this file is empty
 */
bool
NeuroglancerAnnotationFileImporter::isEmpty() const
{
    return false;
}

/**
 * Add file info to data file content information
 * @param dataFileInformation
 *   The data file info structure
 */
void
NeuroglancerAnnotationFileImporter::addToDataFileContentInformation(DataFileContentInformation& dataFileInformation) const
{
    dataFileInformation.addText("Starting Neuroglancer File Information...");
    dataFileInformation.addNameAndValue("Info File Directory", m_infoFileDirectoryName);
    dataFileInformation.addNameAndValue("ByID Directory", m_byIdDirectoryName);
    addShardingToDataFileInformation(dataFileInformation, "By ID Sharding", m_byIdSharding);
    dataFileInformation.addNameAndValue("Dim X", dimensionToString(m_xDimension));
    dataFileInformation.addNameAndValue("Dim Y", dimensionToString(m_yDimension));
    dataFileInformation.addNameAndValue("Dim Z", dimensionToString(m_zDimension));

    const AString annTypeName(FeatureItemTypeEnum::toGuiName(m_annotationType));
    dataFileInformation.addNameAndValue("Annotation Type", annTypeName);
    dataFileInformation.addNameAndValue("Lower Bound", AString::fromNumbers(m_lowerBound));
    dataFileInformation.addNameAndValue("Upper Bound", AString::fromNumbers(m_upperBound));

    for (const Relationship& r : m_relationships) {
        dataFileInformation.addNameAndValue("Relationships ID", r.m_id);
        dataFileInformation.addNameAndValue("Relationships Directory", r.m_directoryName);
        addShardingToDataFileInformation(dataFileInformation, "Relationships Sharding", r.m_sharding);
    }
    
    for (const NeuroglancerProperty& p : m_properties) {
        dataFileInformation.addNameAndValue("Property ID", p.m_id);
        dataFileInformation.addNameAndValue("   Description", p.m_description);
        dataFileInformation.addNameAndValue("   Property Type", neuroglancerDataTypeToString(p.m_propertyType));
        dataFileInformation.addNameAndValue("   Offset", p.m_fileOffset);
        
        if ( ! p.m_enumValueLabel.empty()) {
            for (const auto& mapInfo : p.m_enumValueLabel) {
                dataFileInformation.addNameAndValue("   ", (AString::number(mapInfo.first)
                                                            + " " + mapInfo.second));
            }
        }
    }
}

/**
 * Add description of sharding to data file information
 * @param shardingName
 *    Name of the sharding
 * @param sharding
 *    The sharding instance
 */
void
NeuroglancerAnnotationFileImporter::addShardingToDataFileInformation(DataFileContentInformation& dataFileInformation,
                                                              const AString& shardingName,
                                                              const Sharding& sharding) const
{
    dataFileInformation.addNameAndValue("Sharding Name", shardingName);
    if (sharding.m_validFlag) {
        dataFileInformation.addNameAndValue("  Sharding Type", sharding.m_type);
        dataFileInformation.addNameAndValue("  Sharding Data Encoding", sharding.m_dataEncoding);
        dataFileInformation.addNameAndValue("  Sharding Hash", sharding.m_hash);
        dataFileInformation.addNameAndValue("  Sharding Minishard Bits", sharding.m_minishardBits);
        dataFileInformation.addNameAndValue("  Sharding Minishard Index Encoding", sharding.m_minishardIndexEncoding);
        dataFileInformation.addNameAndValue("  Sharding Preshift Bits", sharding.m_preshiftBits);
        dataFileInformation.addNameAndValue("  Sharding Shard Bits", sharding.m_shardBits);
    }
}

/**
 * Read the data file.
 *
 * @param filename
 *    Name of the data file.
 * @throws DataFileException
 *    If the file was not successfully read.
 */
void
NeuroglancerAnnotationFileImporter::readFile(const AString& filename)
{
    readNeuroglancerInfoFile(filename);
    
    for (const Relationship& r : m_relationships) {
        readNeuroglancerAnnotationShardedFiles(r.m_sharding,
                                               ShardingDataType::RELATIONSHIP,
                                               r.m_directoryName);
    }
    
    if (m_byIdSharding.m_validFlag) {
        /*
         * Multiple annotations are in one or more files
         */
        readNeuroglancerAnnotationShardedFiles(m_byIdSharding,
                                               ShardingDataType::ANNOTATION,
                                               m_byIdDirectoryName);
    }
    else {
        /*
         * Each annotation is in its own file
         */
        readNeuroglancerAnnotationFiles();
    }

    /*
     * Set feature model column titles using property descriptions
     */
    if (m_featureFile->m_featureModel->columnCount() > 0) {
        QStringList headerLabels;
        headerLabels << "Point";
        for (const auto& p : m_properties) {
            headerLabels << p.m_description;
        }
        m_featureFile->m_featureModel->setHeaderLabels(headerLabels);
        
        m_featureFile->m_featureModel->updateCheckedStateOfAllItems();
    }
}

/**
 * Read the neuroglancer "info" file.  The info file (in JSON) describes the contents of the other files.
 *
 * @param filenameIn
 *    Name of the data file.
 * @throws DataFileException
 *    If the file was not successfully read or other errors.
 */
void
NeuroglancerAnnotationFileImporter::readNeuroglancerInfoFile(const AString& filenameIn)
{
   FileInformation fileInfo(filenameIn);
    const AString nameNoPath(fileInfo.getFileName());
    if (nameNoPath != "info") {
        throw DataFileException("Name of file MUST be named \"info\" but is named \""
                                + nameNoPath + "\"");
    }
    
    m_infoFileDirectoryName = fileInfo.getAbsolutePath();
    
//    const AString spatial0DirName(fileInfo.getAbsolutePath()
//                                  + QDir::separator()
//                                  + "spatial0");
    
    AString errorMessage;
        
    if ( ! errorMessage.isEmpty()) {
        throw DataFileException(errorMessage);
    }
    
    /*
     * Open the "info" file
     */
    const AString filename(fileInfo.getAbsoluteFilePath());
    QFile jsonfile(filename);
    if ( ! jsonfile.open(QIODevice::ReadOnly)) {
        throw DataFileException("Error opening "
                                + filename
                                + ": "
                                + jsonfile.errorString());
    }
    
    /*
     * Read the entire "info" file
     */
    QByteArray dataRead(jsonfile.readAll());

    /*
     * Can print to help with debugging
     */
    const bool printJsonFlag(false);
    QString s(dataRead);
    if (printJsonFlag) {
        std::cout << "-->" << s << "<---" << std::endl;
    }
    
    /*
     * Allow Qt to parse the JSON text
     */
    QJsonParseError jsonError;
    QJsonDocument json = QJsonDocument::fromJson(dataRead,
                                                 &jsonError);
    if (jsonError.error != QJsonParseError::NoError) {
        throw DataFileException("Failed to read JSON from "
                                + filename
                                + " with error: "
                                + jsonError.errorString()
                                + " at offset: "
                                + QString::number(jsonError.offset));
    }
    
    /*
     * Can print a "pretty" (formatted with indentation
     * for easier reading) version of the JSON
     */
    const bool prettyPrintFlag(true);
    if (prettyPrintFlag) {
        AString nameOut(FileInformation::assembleFileComponents(fileInfo.getAbsolutePath(),
                                                                "formatted",
                                                                "json"));
        QByteArray jsonOut(json.toJson(QJsonDocument::JsonFormat::Indented));
        QFile fileOut(nameOut);
        if (fileOut.open(QIODevice::WriteOnly)) {
            fileOut.write(jsonOut);
            fileOut.close();
        }
        else {
            throw DataFileException("Error opening " + nameOut
                                    + ": " + fileOut.errorString());
        }
    }
    
    /*
     * Top level item must be a Json Object
     */
    if ( ! json.isObject()) {
        throw DataFileException("Top level JSON in "
                                + filename
                                + " is not a JsonObject");
    }

    try {
        parseNeuroglancerInfoFileJson(fileInfo,
                                      json.object());
        
    }
    catch (const DataFileException& dfe) {
        throw DataFileException("While reading "
                                + filename
                                + ": "
                                + dfe.whatString());
    }
}

/**
 * Parse the Neuroglancer Info file JSON
 * @param topObject
 *    The top-level JSON object
 * @throw DataFileException
 */
void
NeuroglancerAnnotationFileImporter::parseNeuroglancerInfoFileJson(const FileInformation& /*fileInfo*/,
                                                          const QJsonObject& root)
{
    AString errorMessage;
    
    const AString rootTypeName = root.value("@type").toString();
    if (rootTypeName != "neuroglancer_annotations_v1") {
        errorMessage.appendWithNewLine("@type="
                                       + rootTypeName
                                       + "but should be: neuroglancer_annotations_v1");
    }
    
    const QString annTypeName(root.value("annotation_type").toString().toUpper());
    if (annTypeName == "POINT") {
        m_annotationType = FeatureItemTypeEnum::POINT;
    }
    else if (annTypeName == "LINE") {
        m_annotationType = FeatureItemTypeEnum::INVALID;
    }
    else if (annTypeName == "AXIS_ALIGNED_BOUNDING_BOX") {
        m_annotationType = FeatureItemTypeEnum::INVALID;
    }
    else if (annTypeName == "ELLIPSOID") {
        m_annotationType = FeatureItemTypeEnum::INVALID;
    }
    else if (annTypeName == "POLYLINE") {
        m_annotationType = FeatureItemTypeEnum::INVALID;
    }
    
    /*
     * We only support points
     */
    if (m_annotationType == FeatureItemTypeEnum::INVALID) {
        errorMessage.appendWithNewLine("annotation_type="
                                       + annTypeName
                                       + " not supported.");
    }
    
    if ( ! errorMessage.isEmpty()) {
        throw DataFileException(errorMessage);
    }
    
    
    parseByIdObject(root.value("by_id").toObject());

    parseDimensionsObject(root.value("dimensions").toObject());
    
    m_lowerBound = parseFloatArray(root.value("lower_bound").toArray());
    m_upperBound = parseFloatArray(root.value("upper_bound").toArray());

    parsePropertiesArray(root.value("properties").toArray());
    parseSpatialArray(root.value("spatial").toArray());
    parseRelationshipsArray(root.value("relationships").toArray());
}

/**
 * Parse a float array into a float vector
 * @param array
 *   The json array
 * @return
 *    A float vector
 */
std::vector<float>
NeuroglancerAnnotationFileImporter::parseFloatArray(const QJsonArray &array)
{
    std::vector<float> arrayOut;
    arrayOut.reserve(array.size());
    for (const QJsonValue& v : array) {
        arrayOut.push_back(v.toDouble());
    }
    return arrayOut;
}

/**
 * Parse an int array into a int vector
 * @param array
 *   The json array
 * @return
 *    A int vector
 */
std::vector<int32_t>
NeuroglancerAnnotationFileImporter::parseIntArray(const QJsonArray &array)
{
    std::vector<int32_t> arrayOut;
    arrayOut.reserve(array.size());
    for (const QJsonValue& v : array) {
        arrayOut.push_back(v.toInt());
    }
    return arrayOut;
}

/**
 * Parse a dimension object
 * @param dimsObj
 *   The dimensions object
 */
void
NeuroglancerAnnotationFileImporter::parseDimensionsObject(const QJsonObject &dimsObj)
{
    for (auto it = dimsObj.constBegin(); it != dimsObj.constEnd(); ++it) {
        const QJsonArray pair = it.value().toArray();
        const AString dimName(it.key().toLower());
        Axis axis(Axis::X);
        if (dimName == "x") {
            axis = Axis::X;
        }
        else if (dimName == "y") {
            axis = Axis::Y;
        }
        else if (dimName == "z") {
            axis = Axis::Z;
        }
        else {
            throw DataFileException("Unrecogized dimension="
                                    + it.key());
        }
        
        float resolution(0.0);
        Unit unit(Unit::UNITLESS);
        if (pair.size() >= 1) {
            resolution = pair.at(0).toDouble();
        }
        float unitScale = 1.0;
        if (pair.size() >= 2) {
            const QString unitName(pair.at(1).toString().toLower());
            if (unitName == "m") {
                unit = Unit::MILLIMETERS;
                unitScale = 1000;
            }
            else if (unitName == "cm") {
                unit = Unit::MILLIMETERS;
                unitScale = 100;
            }
            else if (unitName == "mm") {
                unit = Unit::MILLIMETERS;
                unitScale = 1.0;
            }
            else if (unitName == "um") {
                unit = Unit::MILLIMETERS;
                unitScale = 0.001;
            }
            else if (unitName == "nm") {
                unit = Unit::MILLIMETERS;
                unitScale = 0.000001;
            }
            else if (unitName == "s") {
                unit = Unit::SECONDS;
            }
            else if (unitName.isEmpty()) {
                unit = Unit::UNITLESS;
            }
            else {
                throw DataFileException("Unsupported unit="
                                        + pair.at(1).toString());
            }
            
            switch (unit) {
                case Unit::MILLIMETERS:
                    break;
                case Unit::SECONDS:
                    throw DataFileException("Seconds not supported for unit");
                    break;
                case Unit::UNITLESS:
                    throw DataFileException("Unitless not supported for unit");
                    break;
            }
        }
        
        Dimension* d(NULL);
        switch (axis) {
            case Axis::X:
                d = &m_xDimension;
                d->m_axis = Axis::X;
                break;
            case Axis::Y:
                d = &m_yDimension;
                d->m_axis = Axis::Y;
                break;
            case Axis::Z:
                d = &m_zDimension;
                d->m_axis = Axis::Z;
                break;
        }
        d->m_units      = unit;
        d->m_unitScale  = unitScale;
        d->m_resolution = resolution;
        d->m_valid      = true;
    }
}

/**
 * Parse the "by_id" object
 * @param The by_id objectr
 */
void
NeuroglancerAnnotationFileImporter::parseByIdObject(const QJsonObject& byIdObject)
{
    const AString byIdDirName(byIdObject.value("key").toString());
    if (byIdDirName.isEmpty()) {
        throw DataFileException("by_id is missing or empty.");
    }
    else {
        m_byIdDirectoryName = (m_infoFileDirectoryName
                               + QDir::separator()
                               + byIdDirName);
        if ( ! QDir(m_byIdDirectoryName).exists()) {
            throw DataFileException("by_id directory does not exist: "
                                    + m_byIdDirectoryName);
        }
    }
    
    if (byIdObject.contains("sharding")) {
        const QJsonObject shardingObject(byIdObject.value("sharding").toObject());
        m_byIdSharding = parseShardingObject(shardingObject);
    }
}

/**
 * Parse a sharding object
 * @param shardingObject
 *    The JSON sharding object
 * @return
 *    Sharding class instance
 */
NeuroglancerAnnotationFileImporter::Sharding
NeuroglancerAnnotationFileImporter::parseShardingObject(const QJsonObject shardingObject)
{
    Sharding sharding;
    sharding.m_type = shardingObject.value("@type").toString();
    sharding.m_dataEncoding = shardingObject.value("data_encoding").toString();
    sharding.m_hash = shardingObject.value("hash").toString();
    sharding.m_minishardBits = shardingObject.value("minishard_bits").toInt();
    sharding.m_minishardIndexEncoding = shardingObject.value("minishard_index_encoding").toString();
    sharding.m_preshiftBits = shardingObject.value("preshift_bits").toInt();
    sharding.m_shardBits = shardingObject.value("shard_bits").toInt();
    
    sharding.m_validFlag = false;
    if (sharding.m_type.isNotEmpty()
        && sharding.m_dataEncoding.isNotEmpty()
        && sharding.m_hash.isNotEmpty()
        && (sharding.m_minishardBits >= 0)
        && sharding.m_minishardIndexEncoding.isNotEmpty()
        && (sharding.m_preshiftBits >= 0)
        && (sharding.m_shardBits >= 0)) {
        sharding.m_validFlag = true;
    }

    return sharding;
}

/**
 * Parse a relationships object
 * @param relationshipsArray
 *   The relationships array
 */
void
NeuroglancerAnnotationFileImporter::parseRelationshipsArray(const QJsonArray& relationshipsArray)
{
    const int32_t numElem(relationshipsArray.count());
    for (int32_t i = 0; i < numElem; i++) {
        Relationship relationship;
        const QJsonObject& relationshipsObject = relationshipsArray.at(i).toObject();
        const AString dirName(relationshipsObject.value("key").toString());
        if (dirName.isNotEmpty()) {
            relationship.m_directoryName = (m_infoFileDirectoryName
                                            + QDir::separator()
                                            + dirName);
            if ( ! QDir(relationship.m_directoryName).exists()) {
                throw DataFileException("relationships directory does not exist: "
                                        + relationship.m_directoryName);
            }
        }
        
        relationship.m_id = relationshipsObject.value("id").toString();
        
        if (relationshipsObject.contains("sharding")) {
            const QJsonObject shardingObject(relationshipsObject.value("sharding").toObject());
            relationship.m_sharding = parseShardingObject(shardingObject);
        }
        m_relationships.push_back(relationship);
    }
}


/**
 * Parse a properties array
 * @param propsArray
 *    The properties array
 */
void
NeuroglancerAnnotationFileImporter::parsePropertiesArray(const QJsonArray &propsArr)
{
    /*
     * m_lowerBound.size() == 3 for XYZ
     */
    int64_t offset(sizeof(float) * m_lowerBound.size());
    switch (m_annotationType) {
        case FeatureItemTypeEnum::INVALID:
            CaretAssert(0);
            break;
        case FeatureItemTypeEnum::POINT:
            /* One XYZ */
            offset *= 1;
            break;
    }
    
    for (const QJsonValue &pv : propsArr) {
        const QJsonObject po = pv.toObject();
        
        const AString id(po.value("id").toString());
        const AString description(po.value("description").toString());
        const AString typeName(po.value("type").toString().toLower());

        NeuroglancerDataType dataType(NeuroglancerDataType::INVALID);
        int32_t dataTypeSize(0);
        if (typeName == "rgb") {
            dataType = NeuroglancerDataType::RGB;
            dataTypeSize = 3;
        }
        else if (typeName == "rgba") {
            dataType = NeuroglancerDataType::RGBA;
            dataTypeSize = 4;
        }
        else if (typeName == "uint8") {
            dataType = NeuroglancerDataType::UINT8;
            dataTypeSize = 1;
        }
        else if (typeName == "int8") {
            dataType = NeuroglancerDataType::INT8;
            dataTypeSize = 1;
        }
        else if (typeName == "uint16") {
            dataType = NeuroglancerDataType::UINT16;
            dataTypeSize = 2;
        }
        else if (typeName == "int16") {
            dataType = NeuroglancerDataType::INT16;
            dataTypeSize = 2;
        }
        else if (typeName == "uint32") {
            dataType = NeuroglancerDataType::UINT32;
            dataTypeSize = 4;
        }
        else if (typeName == "int32") {
            dataType = NeuroglancerDataType::INT32;
            dataTypeSize = 4;
        }
        else if (typeName == "float32") {
            dataType = NeuroglancerDataType::FLOAT32;
            dataTypeSize = 4;
        }
        else {
            throw DataFileException("Unknown type=" + typeName);
        }
        CaretAssert(dataType != NeuroglancerDataType::INVALID);
        
        std::vector<AString> enumLabels;
        if (po.contains("enum_labels")) {
            for (const QJsonValue &lv : po.value("enum_labels").toArray())
                enumLabels.push_back(lv.toString());
        }
        
        std::vector<int32_t> enumValues;
        if (po.contains("enum_values")) {
            enumValues = parseIntArray(po.value("enum_values").toArray());
        }
        
        NeuroglancerProperty property;
        property.m_propertyType = dataType;
        property.m_description = description;
        property.m_id = id;
        property.m_fileOffset = offset;
        property.m_labelModel = NULL;

        if ( ! enumLabels.empty()) {
            if (enumLabels.size() == enumValues.size()) {
                FeatureLabelModel* labelModel(new FeatureLabelModel(description));
                const int32_t numItems(enumLabels.size());
                for (int32_t i = 0; i < numItems; i++) {
                    property.m_enumValueLabel.insert(std::make_pair(enumValues[i],
                                                                    enumLabels[i]));
                    FeatureLabel* label(new FeatureLabel(enumValues[i],
                                                                                       enumLabels[i]));
                    labelModel->addLabel(label);
                }
                m_featureFile->m_labelModels.emplace_back(labelModel);
                property.m_labelModel = labelModel;
            }
            else {
                throw DataFileException("Number of enum values="
                                        + AString::number(enumValues.size())
                                        + " and enum labels="
                                        + AString::number(enumLabels.size())
                                        + " do not match for property: "
                                        + description);
            }
        }

        m_properties.push_back(property);

        offset += dataTypeSize;
    }
}

/**
 * Parse a spatial array
 * @param spatialArray
 *   The spatial array
 * @return
 *   The spatial grid into
 */
std::vector<NeuroglancerAnnotationFileImporter::SpatialGrid>
NeuroglancerAnnotationFileImporter::parseSpatialArray(const QJsonArray &spatialArray)
{
    std::vector<SpatialGrid> grids;
    grids.reserve(spatialArray.size());
    
    for (const QJsonValue &sv : spatialArray) {
        const QJsonObject so = sv.toObject();
        
        SpatialGrid g;
        g.m_path = so.value("key").toString();
        g.m_chunkSize = parseIntArray(so.value("chunk_size").toArray());
        g.m_gridShape = parseIntArray(so.value("grid_shape").toArray());
        g.m_limit = so.value("limit").toInt();
        
        grids.push_back(g);
    }
    return grids;
}

/**
 * Write the data file.
 *
 * @param filename
 *    Name of the data file.
 * @throws DataFileException
 *    If the file was not successfully written.
 */
void
NeuroglancerAnnotationFileImporter::writeFile(const AString& /*filename*/)
{
    throw DataFileException("Writing of Neuroglancer File is not supported.");
}

/**
 * Convert a dimension to a string representation
 * @param dimension
 *    The dimension
 * @return
 *    String describing dimension
 */
AString
NeuroglancerAnnotationFileImporter::dimensionToString(const Dimension& dimension)
{
    AString axisText;
    switch (dimension.m_axis) {
        case Axis::X:
            axisText = "X";
            break;
        case Axis::Y:
            axisText = "Y";
            break;
        case Axis::Z:
            axisText = "Z";
            break;
    }
    
    AString unitText;
    switch (dimension.m_units) {
        case Unit::MILLIMETERS:
            unitText = "Millimeters";
            break;
        case Unit::SECONDS:
            unitText = "Seconds";
            break;
        case Unit::UNITLESS:
            unitText = "Unitless";
            break;
    }
    AString s("Axis=" + axisText
              + ", Unit=" + unitText
              + ", UnitScale=" + AString::number(dimension.m_unitScale)
              + ", Resolution=" + AString::number(dimension.m_resolution));
    
    return s;
}

/**
 * Convert an annotation type to a string representation
 * @param annotationType
 *    The annotation type
 * @return
 *    String describing data type
 */
AString
NeuroglancerAnnotationFileImporter::annotationFileTypeToString(const AnnotationFileType& annotationFileType)
{
    AString annTypeName("Invalid");
    switch (annotationFileType) {
        case AnnotationFileType::AXIS_ALIGNED_BOUNDING_BOX:
            annTypeName = "Axis Aligned Bounding Box";
            break;
        case AnnotationFileType::ELLIPSOID:
            annTypeName = "Ellipsoid";
            break;
        case AnnotationFileType::LINE:
            annTypeName = "Line";
            break;
        case AnnotationFileType::POINT:
            annTypeName = "Point";
            break;
        case AnnotationFileType::POLYLINE:
            annTypeName = "Polyline";
            break;
    }
    return annTypeName;
}

/**
 * Read the data files in the 'byId" directory
 * Each file in the directory contains data for one annotation.
 */
void
NeuroglancerAnnotationFileImporter::readNeuroglancerAnnotationFiles()
{
    QDir dir(m_byIdDirectoryName);
    if ( ! dir.exists()) {
        throw DataFileException("byID directory does not exist: "
                                + m_byIdDirectoryName);
    }
    
    const QStringList filenamesList(dir.entryList(QDir::Files));
    QStringListIterator iter(filenamesList);
    std::vector<AString> annFileNames(filenamesList.begin(),
                                      filenamesList.end());
    AStringNaturalComparison::sortStringVector(annFileNames);
    
    float xScale(1.0);
    float yScale(1.0);
    float zScale(1.0);
    if (m_xDimension.m_valid) {
        xScale = m_xDimension.m_unitScale * m_xDimension.m_resolution;
        CaretAssert(xScale != 0.0);
    }
    if (m_yDimension.m_valid) {
        yScale = m_yDimension.m_unitScale * m_yDimension.m_resolution;
        CaretAssert(yScale != 0.0);
    }
    if (m_zDimension.m_valid) {
        zScale = m_zDimension.m_unitScale * m_zDimension.m_resolution;
        CaretAssert(zScale != 0.0);
    }

    for (const AString& filenameOnly : annFileNames) {
        const AString pathAndName(m_byIdDirectoryName
                                  + QDir::separator()
                                  + filenameOnly);
        QFile file(pathAndName);
        if ( ! file.open(QFile::ReadOnly)) {
            throw DataFileException("Failed to read file "
                                    + pathAndName);
        }
        
        bool validFlag(false);
        const uint64_t filenameInt(filenameOnly.toULong(&validFlag));
        if ( ! validFlag) {
            CaretLogSevere("Failed to convert "
                           + filenameOnly
                           + " to an unsigned long");
        }
        
        /*
         * Use a datastream to read the file
         */
        QDataStream dataStream(&file);
        
        QByteArray emptyByteArray;
        /* probably want readRelationshipDataAfterAnnotationFlag to be true */
        const bool readRelationshipDataAfterAnnotationFlag(false);
        NewAnnoationInformation nfi(readAnnotationFromDataStream(&file,
                                                                 emptyByteArray,
                                                                 dataStream,
                                                                 FeatureItemGroup::getDefaultGroupID(),
                                                                 filenameInt,
                                                                 readRelationshipDataAfterAnnotationFlag));
        /*
         * DO NOT reference nfi.m_featureAndPropertiesList
         * after calling addFeature as it is destroyed if
         * not added to model.
         */
        m_featureFile->addFeature(nfi.m_featureAndPropertiesList);
    }
}

/**
 * Read an annontation from a datastream
 * @param file
 *    File containing annotation.  If NULL, annotation is being read from in-memory data
 * @param dataBytes
 *    If 'file' is NULL, the annotation is being read from this byte array
 * @param dataStream
 *   The datastream
 * @param relationshipID
 *    The relationship that groups this annotation with other annotations
 * @param annotationID
 *    The annotation ID (may be filename when each annotation in its own file)
 * @param readRelationshipDataAfterAnnotationFlag
 *    If true, read relationship data that is after the annotation
 * @return
 *    Name and data for adding to a model
 */
NeuroglancerAnnotationFileImporter::NewAnnoationInformation
NeuroglancerAnnotationFileImporter::readAnnotationFromDataStream(QFile* file,
                                                                 const QByteArray& dataBytes,
                                                                 QDataStream& dataStream,
                                                                 const uint64_t relationshipID,
                                                                 const uint64_t annotationID,
                                                                 const bool readRelationshipDataAfterAnnotationFlag)
{
    /*
     * Position/radii vectors, required by the annotation type, encoded as
     * float32le values:
     *
     *   - POINT:
     *       The position vector.
     *
     *   - LINE:
     *       The first endpoint position, followed by the second endpoint
     *       position.
     *
     *   - AXIS_ALIGNED_BOUNDING_BOX:
     *       The first position, followed by the second position.
     *
     *   - ELLIPSOID:
     *       The center position, followed by the radii vector.
     *
     *   - POLYLINE:
     *       The number of points as a uint32le value, followed by the
     *       position of each point as float32le.
     *
     * Properties, encoded per their type:
     *
     *   - uint32, int32, float32:
     *       Encoded as a little-endian value.
     *
     *   - uint16, int16:
     *       Encoded as a little-endian value.
     *
     *   - uint8, int8, rgb, rgba:
     *       Encoded as-is (no byte-order conversion needed).
     *
     * Padding:
     *   Up to 3 padding bytes (value 0) to align the next field to a
     *   4-byte offset.
     *
     * Below is ONLY when each annotation is in a single file (NOT sharded)
     *
     * Relationships, for each relationship specified in the info JSON file:
     *
     *   1. The number of object IDs, as a uint32le value.
     *   2. Each related object ID, as a uint64le value.
     */
    dataStream.setByteOrder(QDataStream::LittleEndian);
    dataStream.setFloatingPointPrecision(QDataStream::SinglePrecision);
    
    /*
     * The property values are added into same row as the annotation in the model
     */
    QList<QStandardItem*> modelRowPropertyValues;
    
    /*
     * The property values are also added to the annotation
     */
    std::vector<const FeaturePropertyValue*> neuroglancerAnnotationPropertyValues;
    
    float annotationSize(2.0);
    QColor annotationColor(255, 255, 255, 255);
    
    /*
     * We need to track the number of bytes read.  In sharded files,
     * there may be multiple annotations and each new annotation is
     * on a 4-byte boundary.  Thus we may need to skip 1 to 3 bytes
     * after reading an annotation.
     *
     * When reading sharded data, data is read from a QByteArray that
     * is in memory.  A QDataStream reads from the the byte array.
     * Unlike QFile, QDataStream does not provide a "position" function.
     */
    int64_t numberOfBytesRead(0);
    
    float i, j, k;
    dataStream >> i >> j >> k;
    numberOfBytesRead += (sizeof(float) * 3);
    
    const int32_t numProperties(m_properties.size());
    for (int32_t iProp = 0; iProp < numProperties; iProp++) {
        CaretAssertVectorIndex(m_properties, iProp);
        const NeuroglancerProperty& property(m_properties[iProp]);
        
        const int64_t offset(property.m_fileOffset);
        CaretAssert(offset > 0);
        
        FeaturePropertyDataTypeEnum::Enum propertyType(FeaturePropertyDataTypeEnum::INVALID);
        QVariant propertyValue = "InvalidSeekFailed";
        AString propertyLabelText;
            switch (property.m_propertyType) {
                case NeuroglancerDataType::INVALID:
                    propertyType = FeaturePropertyDataTypeEnum::INVALID;
                    propertyValue = "InvalidDataType";
                    break;
                case NeuroglancerDataType::RGB:
                {
                    uint8_t r, g, b;
                    dataStream >> r >> g >> b;
                    QColor color(r, g, b);
                    propertyValue = QVariant::fromValue(color);
                    propertyType = FeaturePropertyDataTypeEnum::RGBA;
                    
                    annotationColor.setRgb(r, g, b);
                    numberOfBytesRead += (sizeof(uint8_t) * 3);
                }
                    break;
                case NeuroglancerDataType::RGBA:
                {
                    uint8_t r, g, b, a;
                    dataStream >> r >> g >> b >> a;
                    QColor color(r, g, b, a);
                    propertyValue = QVariant::fromValue(color);
                    propertyType = FeaturePropertyDataTypeEnum::RGBA;
                    
                    annotationColor.setRgb(r, g, b, a);
                    numberOfBytesRead += (sizeof(uint8_t) * 4);
                }
                    break;
                case NeuroglancerDataType::UINT8:
                {
                    uint8_t v;
                    dataStream >> v;
                    propertyValue = static_cast<uint32_t>(v);
                    propertyType = FeaturePropertyDataTypeEnum::UNSIGNED_INTEGER;
                    numberOfBytesRead += (sizeof(uint8_t) * 1);
                }
                    break;
                case NeuroglancerDataType::INT8:
                {
                    int8_t v;
                    dataStream >> v;
                    propertyValue = static_cast<int32_t>(v);
                    propertyType = FeaturePropertyDataTypeEnum::INTEGER;
                    numberOfBytesRead += (sizeof(int8_t) * 1);
                }
                    break;
                case NeuroglancerDataType::UINT16:
                {
                    uint16_t v;
                    dataStream >> v;
                    propertyValue = static_cast<uint32_t>(v);
                    propertyType = FeaturePropertyDataTypeEnum::UNSIGNED_INTEGER;
                    numberOfBytesRead += (sizeof(uint16_t) * 1);
                }
                    break;
                case NeuroglancerDataType::INT16:
                {
                    int16_t v;
                    dataStream >> v;
                    propertyValue = static_cast<int32_t>(v);
                    propertyType = FeaturePropertyDataTypeEnum::INTEGER;
                    numberOfBytesRead += (sizeof(int16_t) * 1);
                }
                    break;
                case NeuroglancerDataType::UINT32:
                {
                    uint32_t v;
                    dataStream >> v;
                    propertyValue = v;
                    propertyType = FeaturePropertyDataTypeEnum::UNSIGNED_INTEGER;
                    numberOfBytesRead += (sizeof(uint32_t) * 1);
                }
                    break;
                case NeuroglancerDataType::INT32:
                {
                    int32_t v;
                    dataStream >> v;
                    propertyValue = v;
                    propertyType = FeaturePropertyDataTypeEnum::INTEGER;
                    numberOfBytesRead += (sizeof(int32_t) * 1);
                }
                    break;
                case NeuroglancerDataType::FLOAT32:
                {
                    float v;
                    dataStream >> v;
                    propertyValue = v;
                    propertyType = FeaturePropertyDataTypeEnum::FLOAT;
                    numberOfBytesRead += (sizeof(float) * 1);
                }
                    break;
            }
            
            if (property.m_enumValueLabel.empty()) {
                if (property.m_description == "size") {
                    annotationSize = propertyValue.toFloat();
                }
            }
            else {
                int32_t labelIndex(-1);
                switch (propertyType) {
                    case FeaturePropertyDataTypeEnum::INVALID:
                        break;
                    case FeaturePropertyDataTypeEnum::RGBA:
                        break;
                    case FeaturePropertyDataTypeEnum::UNSIGNED_INTEGER:
                        labelIndex = static_cast<int32_t>(propertyValue.toUInt());
                        break;
                    case FeaturePropertyDataTypeEnum::INTEGER:
                        labelIndex = propertyValue.toInt();
                        break;
                    case FeaturePropertyDataTypeEnum::FLOAT:
                        break;
                    case FeaturePropertyDataTypeEnum::LABEL:
                        break;
                }
                
                if (labelIndex >= 0) {
                    auto labelIter(property.m_enumValueLabel.find(labelIndex));
                    if (labelIter != property.m_enumValueLabel.end()) {
                        propertyLabelText = labelIter->second;
                        propertyType = FeaturePropertyDataTypeEnum::LABEL;
                    }
                }
            }
        
        FeaturePropertyValue* fpv(new FeaturePropertyValue(property.m_description,
                                                           propertyType,
                                                           propertyValue,
                                                           propertyLabelText,
                                                           property.m_labelModel));
        modelRowPropertyValues.push_back(fpv);
        neuroglancerAnnotationPropertyValues.push_back(fpv);
    }

    QByteArray extraBytes;
    if (file != NULL) {
        CaretAssert(numberOfBytesRead == file->pos());
        
        /*
         * After reading the annotation, the file position must be at
         * a 4-byte offset (see comment at beginning of this function).
         */
        const int64_t bytesToSkip(file->pos() % 4);
        CaretAssert((bytesToSkip >= 0)
                    && (bytesToSkip <= 3));
        /*
         * QFile::skip() was added in Qt 5.10.0
         */
        const int64_t bytesActuallySkipped(QtFileHelper::safeSkip(file, bytesToSkip));
        if (bytesToSkip != bytesActuallySkipped) {
            CaretLogWarning("Failed to skip bytes at end of reading Neuroglancer Annotation");
        }
        
        if (m_debugFlag) {
            const int64_t bytesLeft(file->size() - file->pos());
            if (bytesLeft > 0) {
                /*
                 * Read the remaining bytes
                 */
                extraBytes.resize(bytesLeft);
                dataStream.readRawData(extraBytes.data(), bytesLeft);
            }
        }
    }
    else {
        const int64_t bytesToSkip(numberOfBytesRead % 4);
        for (int64_t i = 0; i < bytesToSkip; i++) {
            if (dataStream.atEnd()) {
                break;
            }
            uint8_t bt;
            dataStream >> bt;
        }
//        /*
//         * Read any remaining bytes
//         */
//        extraBytes.reserve(256);
//        while (  ! dataStream.atEnd()) {
//            uint8_t bt;
//            dataStream >> bt;
//            extraBytes.push_back(bt);
//        }
//        
//        /*
//         * There is no "pos()" in QDataStream so we need to determine
//         * if we are at a 4-byte boundary and if there is "padding"
//         */
//        const int64_t dataArrayPos(dataBytes.length() - extraBytes.length());
//        const int64_t remainder(dataArrayPos % 4);
//        
//        if (remainder >= 0) {
//            /*
//             * Skip over the padded bytes
//             */
//            if (remainder <= extraBytes.size()) {
//                extraBytes = extraBytes.mid(remainder);
//            }
//            else {
//                extraBytes.clear();
//            }
//        }
    }
    
    if ( ! extraBytes.isEmpty()) {
        std::cout << "Annotation: " << getFileName() << " has extra bytes at end, num="
        << extraBytes.size() << " mod 4=" << (extraBytes.size() % 4) << std::endl;
    }
    
    if (readRelationshipDataAfterAnnotationFlag) {
        if ( ! m_relationships.empty()) {
            if (extraBytes.size() >= 4) {
                /*
                 * For each relationship specified by the info JSON file:
                 *   The number of object ids as a uint32le value.
                 *   Each related object id, as a uint64le value.
                 */
                QDataStream relStream(extraBytes);
                relStream.setByteOrder(QDataStream::LittleEndian);
                relStream.setFloatingPointPrecision(QDataStream::SinglePrecision);
                
                uint32_t numberOfObjectIDs;
                relStream >> numberOfObjectIDs;
                std::cout << "Annotation ID=" << annotationID << " has count relationship IDs="
                << numberOfObjectIDs << std::endl;
                
                for (uint32_t i = 0; i < numberOfObjectIDs; i++) {
                    quint64 id; /* cannot use uint64_t on Linux */
                    relStream >> id;
                    std::cout << " " << id;
                }
                std::cout << std::endl;
            }
        }
    }
    
    bool supportedFlag(false);
    switch (m_annotationType) {
        case FeatureItemTypeEnum::INVALID:
            break;
        case FeatureItemTypeEnum::POINT:
            supportedFlag = true;
            break;
    }
    if ( ! supportedFlag) {
        throw DataFileException("Neuroglancer Annotation type not supported for "
                                + FeatureItemTypeEnum::toGuiName(m_annotationType));
    }
    
    std::vector<Vector3D> ijks { Vector3D(i, j, k) };
    
    /*
     * Create the annotation
     */
    FeatureItem* na = new FeatureItem(m_annotationType,
                                      relationshipID,
                                      annotationID,
                                      ijks,
                                      annotationColor,
                                      annotationSize,
                                      neuroglancerAnnotationPropertyValues);

    /*
     * The annotation and properties must be inserted
     * as a row.  There does not appear to be a way
     * to add columns to a stadard item and keep them
     * in the same row.
     */
    QList<QStandardItem*> newRow;
    newRow.push_back(na);
    newRow.append(modelRowPropertyValues);
    
    NewAnnoationInformation nfi(annotationID,
                              newRow);
    return nfi;
}


/**
 * Read the sharded data files for the given sharding data type
 * Sharded files contain one or more annotations in a single file.
 * @param shardingInfo
 *    The sharding info
 * @param shardingDataType
 *    Type of data stored in sharding
 * @param shardingDataDirectoryName
 *    Name of directory containing the sharded data
 */
void
NeuroglancerAnnotationFileImporter::readNeuroglancerAnnotationShardedFiles(const Sharding& shardingInfo,
                                                                    const ShardingDataType shardingDataType,
                                                                    const AString& shardingDataDirectoryName)
{
    QDir dir(shardingDataDirectoryName);
    if ( ! dir.exists()) {
        throw DataFileException("Read sharding directory does not exist: "
                                + shardingDataDirectoryName);
    }
    
    /*
     * For each shard number in the range [0, 2**shard_bits), there is a
     * <shard>.shard file, where <shard> is the lowercase base-16 shard number
     * zero padded to ceil(shard_bits/4) digits.
     */
    const int32_t numShardFiles(std::exp2(shardingInfo.m_shardBits));
    if (m_debugFlag) std::cout << "Num shard files: " << numShardFiles << std::endl;
    const int32_t numDigitsInFileName(std::ceil(shardingInfo.m_shardBits / 4));
    if (m_debugFlag)std::cout << "   Num digits in filename: " << numDigitsInFileName << std::endl;

    std::vector<AString> allShardFileNames;
    for (int32_t iFile = 0; iFile < numShardFiles; iFile++) {
        /*
         * Create filename from number with zero padding at beginning of filename
         * Filenames are in form "#.shard" where "#" is one or more digits
         * with leading zeros.
         */
        const AString filenameNumber(AString::number(iFile).rightJustified(numDigitsInFileName, '0'));
        const AString filenameOnly(filenameNumber + ".shard");
        const AString pathAndName(shardingDataDirectoryName
                                  + QDir::separator()
                                  + filenameOnly);
        allShardFileNames.push_back(pathAndName);
    }
    
    AStringNaturalComparison::sortStringVector(allShardFileNames);
    if (m_debugFlag)std::cout << "Sorted shard filenames" << std::endl;
    for (const AString& name : allShardFileNames) {
        if (m_debugFlag)std::cout << "   " << name << std::endl;
    }
    
    float xScale(1.0);
    float yScale(1.0);
    float zScale(1.0);
    if (m_xDimension.m_valid) {
        xScale = m_xDimension.m_unitScale * m_xDimension.m_resolution;
        CaretAssert(xScale != 0.0);
    }
    if (m_yDimension.m_valid) {
        yScale = m_yDimension.m_unitScale * m_yDimension.m_resolution;
        CaretAssert(yScale != 0.0);
    }
    if (m_zDimension.m_valid) {
        zScale = m_zDimension.m_unitScale * m_zDimension.m_resolution;
        CaretAssert(zScale != 0.0);
    }
    
    for (const AString& shardFileName : allShardFileNames) {
        if (m_debugFlag) std::cout << "Processing shareded annotations file: " << shardFileName << std::endl;
        
        QFile file(shardFileName);
        if ( ! file.open(QFile::ReadOnly)) {
            throw DataFileException("Failed to read file "
                                    + shardFileName);
        }
        if (m_debugFlag) std::cout << "File length: " << file.size() << std::endl;
        
        /*
         * Neuorglancer files are LITTLE ENDIAN Single Precision
         */
        QDataStream dataStream(&file);
        dataStream.setByteOrder(QDataStream::LittleEndian);
        dataStream.setFloatingPointPrecision(QDataStream::SinglePrecision);
        
        /*
         * From https://github.com/google/neuroglancer/blob/master/src/datasource/precomputed/sharded.md
         *
         * The first 2**minishard_bits * 16 bytes of each shard file is the
         * "shard index" consisting of 2**minishard_bits entries of the form:
         * - start_offset: uint64le, specifies the inclusive start byte offset
         *   of the "minishard index" in the shard file.
         * - end_offset: uint64le, specifies the exclusive end byte offset of the
         *   "minishard index" in the shard file.
         * Both the start_offset and end_offset are relative to the end of the
         * "shard index", i.e. shard_index_end = 2**minishard_bits * 16 bytes.
         *
         * That is, the encoded "minishard index" for a given minishard is stored
         * in the byte range [shard_index_end + start_offset, shard_index_end + end_offset)
         * of the shard file. A zero-length byte range indicates that there are no
         * chunk IDs in the minishard.
         */
        if (m_debugFlag) std::cout << "2**4: " << std::exp2(4.0) << std::endl;
        if (m_debugFlag) shardingInfo.print("By ID Sharding");
        const int64_t numEntries(std::exp2(shardingInfo.m_minishardBits));
        const int64_t shardIndexLength(numEntries * 16);
        const int64_t shardIndexEnd(shardIndexLength);
        if (m_debugFlag) std::cout << "   Num Entries: " << numEntries << std::endl;
        if (m_debugFlag) std::cout << "   Shard Index Length: " << shardIndexLength << std::endl;
        
        /*
         * Read the start and end offsets of the shards
         */
        std::vector<std::pair<uint64_t, uint64_t>> minishardStartOffsetAndLength;
        for (int64_t i = 0; i < numEntries; i++) {
            quint64 startOffset, endOffset; /* cannot use uint64_t on Linux */
            dataStream >> startOffset >> endOffset;
            startOffset += shardIndexEnd;
            endOffset   += shardIndexEnd;
            const uint64_t minishardLength(endOffset - startOffset);
            if (m_debugFlag) std::cout << "   entry i: startOffset=" << std::hex << startOffset << ", endOffset=" << endOffset
            << std::dec << ", length=" << minishardLength << std::endl;
            if (minishardLength > 0) {
                minishardStartOffsetAndLength.push_back(std::make_pair(startOffset,
                                                                       minishardLength));
            }
        }
        
        /*
         * Read the minishards.  Must be done after reading start and
         * ending offset since reading minishard changes file read
         * position.
         */
        for (const auto& offsetAndLength : minishardStartOffsetAndLength) {
            const uint64_t startOffset(offsetAndLength.first);
            const uint64_t minishardLength(offsetAndLength.second);
            readEncodedMinishardIndex(file,
                                      shardingDataType,
                                      shardingInfo.m_dataEncoding,
                                      shardIndexEnd,
                                      shardingInfo.m_minishardIndexEncoding,
                                      startOffset,
                                      minishardLength);
        }
    }
}

/**
 * Read the encoded minishard index
 * @param file
 *    The QFile that is being read
 * @param shardingDataType
 *    The sharding data type
 * @param dataEncoding
 *    Type of encoding used to compress data
 * @param shardIndexEnd
 *    End of shard index
 * @param minishardIndexEncoding
 *    Encoding for the minishard indexing
 * @param minishardOffset
 *    The location of the minishard in the file
 * @param minishardLength
 *    Length of the minishard
 */
void
NeuroglancerAnnotationFileImporter::readEncodedMinishardIndex(QFile& file,
                                                       const ShardingDataType shardingDataType,
                                                       const AString& dataEncoding,
                                                       const uint64_t shardIndexEnd,
                                                       const AString& minishardIndexEncoding,
                                                       const uint64_t minishardOffset,
                                                       const uint64_t minishardLength)
{
    if (minishardLength <= 0) {
        return;
    }
    
    QByteArray uncompressedData;
    
    QByteArray compressedData;
    compressedData.resize(minishardLength);
    
    if (m_debugFlag) std::cout << "-------------------------------" << std::endl;
    if (m_debugFlag) std::cout << "Seeking to minishard offset: hex=" << std::hex << minishardOffset
       << ", dec=" << std::dec << minishardOffset<< std::endl;
    if (file.seek(minishardOffset)) {
        /*
         * Read the data (probably compressed)
         */
        const uint64_t numRead(file.read(compressedData.data(),
                                         minishardLength));
        if (numRead != minishardLength) {
            throw DataFileException("Failed to read "
                                    + AString::number(minishardLength)
                                    + " bytes.  Actually read"
                                    + AString::number(numRead)
                                    + " bytes from " + file.fileName());
        }
        
        /*
         * Decompress the minishard data
         */
        if ( ! decompressData(compressedData,
                              uncompressedData,
                              minishardIndexEncoding)) {
            return;
        }
        
        if (m_debugFlag) std::cout << "Length compressed=" << compressedData.length()
           << " uncompressed=" << uncompressedData.length() << std::endl;
        
        std::vector<ChunkInfo> minishardChunkInfo;
        processMinishardIndex(file,
                              shardingDataType,
                              shardIndexEnd,
                              uncompressedData,
                              dataEncoding,
                              minishardChunkInfo);
        
        readChunksFromShardFile(file,
                                shardingDataType,
                                dataEncoding,
                                minishardChunkInfo);
        
    }
    else {
        throw DataFileException("Failed to seek to "
                                + AString::number(minishardOffset)
                                + " in " + file.fileName());
    }
}

/**
 * Process a minishard
 * @param file
 *    The QFile that is being read
 * @param shardingDataType
 *    The sharding data type
 * @param shardIndexEnd
 *    End of shard index
 * @param minishardIndexData
 *    Data in the minishard index
 * @param dataEncoding
 *    Encoding of the chunk data
 * @param miniShardChunkInfoOut
 *    Output contains chunk info from the minishard index
 */
void
NeuroglancerAnnotationFileImporter::processMinishardIndex(QFile& file,
                                                   const ShardingDataType shardingDataType,
                                                   const uint64_t shardIndexEnd,
                                                   const QByteArray& minishardIndexData,
                                                   const AString& dataEncoding,
                                                   std::vector<ChunkInfo>& miniShardChunkInfoOut)
{
    /*
     * The "minishard index" stored in the shard file is encoded according to the
     * minishard_index_encoding metadata value. The decoded "minishard index" is a
     * binary string of 24*n bytes, specifying a contiguous C-order array of [3, n]
     * uint64le values. Values array[0, 0], ..., array[0, n-1] specify the chunk IDs
     * in the minishard, and are delta encoded, such that array[0, 0] is equal to the
     * ID of the first chunk, and the ID of chunk i is equal to the sum of
     * array[0, 0], ..., array[0, i]. The size of the data for chunk i is stored as
     * array[2, i]. Values array[1, 0], ..., array[1, n-1] specify the starting
     * offsets in the shard file of the data corresponding to each chunk, and are
     * also delta encoded relative to the end of the prior chunk, such that the
     * starting offset of the first chunk is equal to shard_index_end + array[1, 0],
     * and the starting offset of chunk i is the sum of
     * shard_index_end + array[1, 0], ..., array[1, i] and array[2, 0], ..., array[2, i-1].
     *
     * The start and size values in the minishard index specify the location in the
     * shard file of the chunk data, which is encoded according to the data_encoding
     * metadata value.
     */
    
    miniShardChunkInfoOut.clear();
    
    if (m_debugFlag) std::cout << "Minishard Index Data Length: " << minishardIndexData.length() << std::endl;
    
    QDataStream dataStream(minishardIndexData);
    dataStream.setByteOrder(QDataStream::LittleEndian);
    
    const int64_t numChunks(minishardIndexData.length() / 24);
    const int64_t remainder(minishardIndexData.length() % 24);
    if (remainder != 0) {
        throw DataFileException("ERROR: minishard is not evenly divisible by 24, remainder="
                                + AString::number(remainder));
        return;
    }
    
    miniShardChunkInfoOut.resize(numChunks);
    
    /*
     * Row zero (dim i=0) contains chunk IDs
     * A chunkID is relative to the previous chunk ID
     */
    uint64_t previousChunkID(0);
    for (int64_t iChunk = 0; iChunk < numChunks; iChunk++) {
        if (dataStream.atEnd()) {
            throw DataFileException("End of stream at dim i=0 iChunk="
                                    + AString::number(iChunk));
        }
        quint64 chunkID;  /* cannot use uint64_t on Linux */
        dataStream >> chunkID;
        
        chunkID += previousChunkID;
        previousChunkID = chunkID;
        

        CaretAssertVectorIndex(miniShardChunkInfoOut, iChunk);
        miniShardChunkInfoOut[iChunk].m_id = chunkID;
    }
    
    /*
     * Row one (dim i=1) contains offsets that are
     * relative to the END of the previous chunk
     */
    for (int64_t iChunk = 0; iChunk < numChunks; iChunk++) {
        if (dataStream.atEnd()) {
            throw DataFileException("End of stream at dim i=1 iChunk="
                                    + AString::number(iChunk));
        }
        quint64 chunkOffset;  /* cannot use uint64_t on Linux */
        dataStream >> chunkOffset;
        miniShardChunkInfoOut[iChunk].m_relativeOffset = chunkOffset;
    }
    
    /*
     * Row two (dim i=2) contains sizes of the chunks
     */
    for (int64_t iChunk = 0; iChunk < numChunks; iChunk++) {
        if (dataStream.atEnd()) {
            throw DataFileException("End of stream at dim i=2 iChunk="
                                    + AString::number(iChunk));
        }
        quint64 chunkSize;  /* cannot use uint64_t on Linux */
        dataStream >> chunkSize;
        
        CaretAssertVectorIndex(miniShardChunkInfoOut, iChunk);
        miniShardChunkInfoOut[iChunk].m_size = chunkSize;
    }
    
    /*
     * Now that we have sizes we can compute offsets
     * to absolute positions in the file
     */
    int64_t previousChunkEndOffset(shardIndexEnd);
    for (int64_t iChunk = 0; iChunk < numChunks; iChunk++) {
        CaretAssertVectorIndex(miniShardChunkInfoOut, iChunk);
        ChunkInfo& ci(miniShardChunkInfoOut[iChunk]);
        ci.m_offset = previousChunkEndOffset + ci.m_relativeOffset;
        
        previousChunkEndOffset = ci.m_offset + ci.m_size;
    }
    
    if (m_debugFlag) {
        for (int64_t iChunk = 0; iChunk < numChunks; iChunk++) {
            CaretAssertVectorIndex(miniShardChunkInfoOut, iChunk);
            const ChunkInfo& ci(miniShardChunkInfoOut[iChunk]);
            if (m_debugFlag) std::cout << "Chunk " << iChunk
                << ": id=" << ci.m_id << ", offset=" << ci.m_offset
                << ", rel offset=" << ci.m_relativeOffset
                << ", size=" << ci.m_size << std::endl;;
        }
    }
}

/**
 * Read data (annotations) from the chunks from the shard file
 * @param file
 *    The QFile that is being read
 * @param shardingDataType
 *    The sharding data type
 * @param dataEncoding
 *    Encoding of the chunk data
 * @param miniShardChunkInfo
 *    Info about each chunk
 */
void
NeuroglancerAnnotationFileImporter::readChunksFromShardFile(QFile& file,
                                                     const ShardingDataType shardingDataType,
                                                     const AString& dataEncoding,
                                                     const std::vector<ChunkInfo>& miniShardChunkInfo)
{
    const int64_t numChunks(miniShardChunkInfo.size());
    for (int64_t i = 0; i < numChunks; i++) {
        CaretAssertVectorIndex(miniShardChunkInfo, i);
        const ChunkInfo& chunk(miniShardChunkInfo[i]);
        
        /*
         * Seek to the location of the chunk in the file.
         */
        if (file.seek(chunk.m_offset)) {
            QByteArray compressedData(file.read(chunk.m_size));
            
            QByteArray data;
            if ( ! decompressData(compressedData,
                                  data,
                                  dataEncoding)) {
                return;
            }
            
            /*
             * The chunk contains one annotation so read it
             */
            QDataStream dataStream(data);
            
            switch (shardingDataType) {
                case ShardingDataType::ANNOTATION:
                {
                    QFile* nullFile(NULL);
                    const bool readRelationshipDataAfterAnnotationFlag(false);
                    NewAnnoationInformation nfi(readAnnotationFromDataStream(nullFile,
                                                                             data,
                                                                             dataStream,
                                                                             FeatureItemGroup::getDefaultGroupID(),
                                                                             chunk.m_id,
                                                                             readRelationshipDataAfterAnnotationFlag));

                    /*
                     * DO NOT reference nfi.m_featureAndPropertiesList
                     * after calling addFeature as it is destroyed if
                     * not added to model.
                     */
                    m_featureFile->addFeature(nfi.m_featureAndPropertiesList);
                }
                    break;
                case ShardingDataType::RELATIONSHIP:
                    readRelationshipsFromDataStream(data,
                                                    dataStream,
                                                    chunk.m_id);
                    break;
            }
        }
        else {
            throw DataFileException("Failed to seek to "
            + AString::number(chunk.m_offset)
                                    + " for chunk "
                                    + AString::number(i));
        }
    }
}

/**
 * Decompress data using the given encoding name.
 * @param compressedDataIn
 *   The input compressed data
 * @param uncompressedDataOut
 *   The output uncompressed data if successful.
 * @param encodingName
 *   Name of the compression encoding
 * @return
 *   True if sucessful, else false.
 */
bool
NeuroglancerAnnotationFileImporter::decompressData(const QByteArray& compressedDataIn,
                                            QByteArray& uncompressedDataOut,
                                            const AString encodingName)
{
    if (encodingName == "gzip") {
        /*
         * Use GZIP decompression
         */
        if ( ! DataCompressZLib::uncompressData(compressedDataIn,
                                                uncompressedDataOut)) {
            throw DataFileException(" DataCompressZLib::gzipDecompress() failed");
        }
        return true;
    }
    else if ((encodingName == "raw")
             || encodingName.isEmpty()) {
        /*
         * No compression, output is simply input
         * Note: identical QByteArrays share data until one is changed
         * so no copying of data.
         */
        uncompressedDataOut = compressedDataIn;
        return true;
    }
    else {
        throw DataFileException("Unsupported encoding compression type="
                                + encodingName);
    }
    return false;
}

/**
 * Read a relationship from a datastream
 * @param data
 *    The data
 * @param dataStream
 *    The datastream wrapped around 'data'
 * @param relationshipID
 *    The relationship ID (may be filename when each annotation in its own file)
 */
void
NeuroglancerAnnotationFileImporter::readRelationshipsFromDataStream(const QByteArray& data,
                                                                    QDataStream& dataStream,
                                                                    const uint64_t relationshipID)
{
    /*
     * Multiple annotation encoding
     * Both the related object id index and the spatial index encode lists of
     * annotations in the following binary format:
     * The number of annotations, `count`, as a uint64le value.
     * Repeated for `i = 0` up to `count - 1`:
     *
     * - The position/radii vectors, the property values, and padding bytes of
     *   the `i`th annotation are encoded exactly as in the single annotation
     *   encoding:
     *   https://github.com/google/neuroglancer/blob/master/src/datasource/precomputed/annotations.md#single-annotation-encoding
     *
     * Repeated for `i = 0` up to `count - 1`:
     *
     * - The annotation id of the `i`th annotation encoded as a uint64le value.
     *
     * For the related object id index, the order of the annotations does not
     * matter. For the spatial index, the annotations should be ordered
     * randomly.
     */

    dataStream.setByteOrder(QDataStream::LittleEndian);
    dataStream.setFloatingPointPrecision(QDataStream::SinglePrecision);
    
    uint64_t numAnn;   /* cannot use uint64_t on Linux */
    dataStream >> numAnn;
    if (m_debugFlag) {
        std::cout << "Relation ID=" << relationshipID
        << ", length=" << data.length()
        << ", num ann= " << numAnn << std::endl;
    }

    /*
     * Read the annotations
     */
    std::vector<NewAnnoationInformation> newAnnotationInfo;
    for (uint64_t i = 0; i < numAnn; i++) {
        QFile* nullFile(NULL);
        const bool readRelationshipDataAfterAnnotationFlag(false);
        uint64_t temporaryID(i); /* replaced in next loop */
        const NewAnnoationInformation nfi(readAnnotationFromDataStream(nullFile,
                                                                       data,
                                                                       dataStream,
                                                                       relationshipID,
                                                                       temporaryID,
                                                                       readRelationshipDataAfterAnnotationFlag));
        newAnnotationInfo.push_back(nfi);
    }
    
    /*
     * Now read the annotation IDs and assign IDs to annotation
     */
    for (uint64_t i = 0; i < numAnn; i++) {
        quint64 annID;  /* cannot use uint64_t on Linux */
        dataStream >> annID;
        
        CaretAssertVectorIndex(newAnnotationInfo, (int32_t)i);
        FeatureItem* featureItem(dynamic_cast<FeatureItem*>(newAnnotationInfo[i].m_featureAndPropertiesList[0]));
        CaretAssert(featureItem);
        featureItem->setUniqueID(annID);
        
        /*
         * DO NOT reference newAnnotationInfo[i].m_featureAndPropertiesList
         * after calling addFeature as it is destroyed if
         * not added to model.
         */
        m_featureFile->addFeature(newAnnotationInfo[i].m_featureAndPropertiesList);
    }
}

/**
 * Convert a neuroglancer data type to a string representation
 * @param dataType
 *    The data type
 * @return
 *    String describing data type
 */
AString
NeuroglancerAnnotationFileImporter::neuroglancerDataTypeToString(const NeuroglancerDataType& dataType)
{
    AString dataTypeName;
    switch (dataType) {
        case NeuroglancerDataType::INVALID:
            dataTypeName = "Invalid";
            break;
        case NeuroglancerDataType::RGB:
            dataTypeName = "RGB";
            break;
        case NeuroglancerDataType::RGBA:
            dataTypeName = "RGBA";
            break;
        case NeuroglancerDataType::UINT8:
            dataTypeName = "UINT8";
            break;
        case NeuroglancerDataType::INT8:
            dataTypeName = "INT8";
            break;
        case NeuroglancerDataType::UINT16:
            dataTypeName = "UINT16";
            break;
        case NeuroglancerDataType::INT16:
            dataTypeName = "INT16";
            break;
        case NeuroglancerDataType::UINT32:
            dataTypeName = "UINT32";
            break;
        case NeuroglancerDataType::INT32:
            dataTypeName = "INT32";
            break;
        case NeuroglancerDataType::FLOAT32:
            dataTypeName = "FLOAT32";
            break;
    }
    
    return dataTypeName;
}

/* =========================================================== */

/**
 * Print the sharding information
 * @param name
 *    Name of sharding
 */
void
NeuroglancerAnnotationFileImporter::Sharding::print(const AString& name) const
{
    std::cout << "Sharding " << name << std::endl;
    std::cout << "  m_type:" << m_type << std::endl;
    std::cout << "  m_dataEncoding:" << m_dataEncoding << std::endl;
    std::cout << "  m_hash:" << m_hash << std::endl;
    std::cout << "  m_minishardBits:" << m_minishardBits << std::endl;
    std::cout << "  m_minishardIndexEncoding:" << m_minishardIndexEncoding << std::endl;
    std::cout << "  m_preshiftBits:" << m_preshiftBits << std::endl;
    std::cout << "  m_shardBits:" << m_shardBits << std::endl;
    std::cout << "  m_validFlag:" << AString::fromBool(m_validFlag) << std::endl;
}
