
/*LICENSE_START*/
/*
 *  Copyright (C) 2026 Washington University School of Medicine
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */
/*LICENSE_END*/

#define __NEUROGLANCER_PINS_FILE_DECLARE__
#include "NeuroglancerAnnotationsFile.h"
#undef __NEUROGLANCER_PINS_FILE_DECLARE__

#include <QDataStream>
#include <QDir>
#include <QFile>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonValue>
#include <QStandardItemModel>

#include "AStringNaturalComparison.h"
#include "CaretAssert.h"
#include "CaretDataFileSelectionModel.h"
#include "DataFileException.h"
#include "DataFileContentInformation.h"
#include "EventManager.h"
#include "FileInformation.h"
#include "GiftiMetaData.h"
#include "NeuroglancerAnnotation.h"
#include "NeuroglancerAnnotationPropertyValue.h"
#include "SceneClass.h"
#include "SceneClassAssistant.h"
#include "VolumeFile.h"

using namespace caret;


    
/**
 * \class caret::NeuroglancerAnnotationsFile 
 * \brief Neuroglancer pins file
 * \ingroup Files
 *
 * https://github.com/google/neuroglancer/blob/master/src/datasource/precomputed/annotations.md
 *
 * JSON reading code initially generated by Claude.
 */

/**
 * Constructor.
 */
NeuroglancerAnnotationsFile::NeuroglancerAnnotationsFile()
: CaretDataFile(DataFileTypeEnum::NEUROGLANCER_ANNOTATION)
{
    m_fileMetaData.reset(new GiftiMetaData());
    m_sceneAssistant = std::unique_ptr<SceneClassAssistant>(new SceneClassAssistant());
    
    m_model.reset(new QStandardItemModel());
    
    m_volumeFileSelectionModel.reset(CaretDataFileSelectionModel::newInstanceForCaretDataFileTypes( { DataFileTypeEnum::VOLUME },
                                                                                                   { SubvolumeAttributes::VolumeType::ANATOMY } ));
    
    m_sceneAssistant->add("m_volumeFileSelectionModel",
                          "CaretDataFileSelectionModel",
                          m_volumeFileSelectionModel.get());
    
//    EventManager::get()->addEventListener(this, EventTypeEnum::);
}

/**
 * Destructor.
 */
NeuroglancerAnnotationsFile::~NeuroglancerAnnotationsFile()
{
    EventManager::get()->removeAllEventsFromListener(this);
}

/**
 * Receive an event.
 *
 * @param event
 *    An event for which this instance is listening.
 */
void
NeuroglancerAnnotationsFile::receiveEvent(Event* /*event*/)
{
//    if (event->getEventType() == EventTypeEnum::) {
//        <EVENT_CLASS_NAME*> eventName = dynamic_cast<EVENT_CLASS_NAME*>(event);
//        CaretAssert(eventName);
//
//        event->setEventProcessed();
//    }
}
 
/**
 * @return True if this file is empty
 */
bool
NeuroglancerAnnotationsFile::isEmpty() const
{
    return (m_model->rowCount() == 0);
}

/**
 * @return The structure for this file.
 */
StructureEnum::Enum
NeuroglancerAnnotationsFile::getStructure() const
{
    return StructureEnum::INVALID;
}

/**
 * Set the structure for this file.
 * @param structure
 *   New structure for this file.
 */
void
NeuroglancerAnnotationsFile::setStructure(const StructureEnum::Enum /*structure*/)
{
    /* structure not supported */
}

/**
 * @return Get access to the file's metadata.
 */
GiftiMetaData*
NeuroglancerAnnotationsFile::getFileMetaData()
{
    return m_fileMetaData.get();
}

/**
 * @return Get access to unmodifiable file's metadata.
 */
const GiftiMetaData*
NeuroglancerAnnotationsFile::getFileMetaData() const
{
    return m_fileMetaData.get();
}

/**
 * @return True if file supports file metadata, else false.
 */

bool
NeuroglancerAnnotationsFile::supportsFileMetaData() const
{
    return false;
}

/**
 * @return Selection model for volume that maps voxel indices to stereotaxic coordinates
 */
CaretDataFileSelectionModel*
NeuroglancerAnnotationsFile::getVolumeFileSelectionModel()
{
    return m_volumeFileSelectionModel.get();
}

/**
 * @return Selection model for volume that maps voxel indices to stereotaxic coordinates (const method)
 */
const CaretDataFileSelectionModel*
NeuroglancerAnnotationsFile::getVolumeFileSelectionModel() const
{
    return m_volumeFileSelectionModel.get();
}

/**
 * Add file info to data file content information
 * @param dataFileInformation
 *   The data file info structure
 */
void
NeuroglancerAnnotationsFile::addToDataFileContentInformation(DataFileContentInformation& dataFileInformation) const
{
    CaretDataFile::addToDataFileContentInformation(dataFileInformation);
    
    dataFileInformation.addNameAndValue("Info File Directory", m_infoFileDirectoryName);
    dataFileInformation.addNameAndValue("ByID Directory", m_byIdDirectoryName);
    dataFileInformation.addNameAndValue("Dim X", dimensionToString(m_xDimension));
    dataFileInformation.addNameAndValue("Dim Y", dimensionToString(m_yDimension));
    dataFileInformation.addNameAndValue("Dim Z", dimensionToString(m_zDimension));

    const AString annTypeName(NeuroglancerAnnotationTypeEnum::toGuiName(m_annotationType));
    dataFileInformation.addNameAndValue("Annotation Type", annTypeName);
    dataFileInformation.addNameAndValue("Lower Bound", AString::fromNumbers(m_lowerBound));
    dataFileInformation.addNameAndValue("Upper Bound", AString::fromNumbers(m_upperBound));

    for (const Property& p : m_properties) {
        dataFileInformation.addNameAndValue("Property ID", p.m_id);
        dataFileInformation.addNameAndValue("   Description", p.m_description);
        dataFileInformation.addNameAndValue("   Property Type", dataTypeToString(p.m_propertyType));
        dataFileInformation.addNameAndValue("   Offset", p.m_fileOffset);
        
        if ( ! p.m_enumValueLabel.empty()) {
            for (const auto& mapInfo : p.m_enumValueLabel) {
                dataFileInformation.addNameAndValue("   ", (AString::number(mapInfo.first)
                                                            + " " + mapInfo.second));
            }
        }
        /*
         DataType m_propertyType = DataType::INVALID;
         AString m_description;
         AString m_id;
         std::map<int32_t, AString> m_enumValueLabel;
         int64_t m_fileOffset = -1;

         */
    }
    
    const int32_t numRows(m_model->rowCount());
    dataFileInformation.addNameAndValue("Number of annotations", AString::number(numRows));
    const int32_t numCols(m_model->columnCount());
    for (int32_t iRow = 0; iRow < numRows; iRow++) {
        for (int32_t jCol = 0; jCol < numCols; jCol++) {
            const QStandardItem* item(m_model->item(iRow, jCol));
            const NeuroglancerAnnotationBase* nab(dynamic_cast<const NeuroglancerAnnotationBase*>(item));
            if (nab != NULL) {
                const AString indent((jCol == 0)
                                     ? AString::number(iRow)
                                     : "   ");
                dataFileInformation.addNameAndValue(indent,
                                                    nab->toString());
            }
        }
    }
}

/**
 * @return True if file supports writing, else false.
 */
bool
NeuroglancerAnnotationsFile::supportsWriting() const
{
    return false;
}

/**
 * Read the data file.
 *
 * @param filename
 *    Name of the data file.
 * @throws DataFileException
 *    If the file was not successfully read.
 */
void
NeuroglancerAnnotationsFile::readFile(const AString& filename)
{
    clear();
    
    setFileName(filename);
    
    readNeuroglancerFile(filename);
    
    DataFileContentInformation dfci;
    
    readNeuroglancerAnnotationFiles();

    addToDataFileContentInformation(dfci);
    
    clearModified();
}

/**
 * Read the neuroglancer pins file.
 *
 * @param filenameIn
 *    Name of the data file.
 * @throws DataFileException
 *    If the file was not successfully read.
 */
void
NeuroglancerAnnotationsFile::readNeuroglancerFile(const AString& filenameIn)
{
   FileInformation fileInfo(filenameIn);
    const AString nameNoPath(fileInfo.getFileName());
    if (nameNoPath != "info") {
        throw DataFileException("Name of file MUST be named \"info\" but is named \""
                                + nameNoPath + "\"");
    }
    
    m_infoFileDirectoryName = fileInfo.getAbsolutePath();
    
//    const AString spatial0DirName(fileInfo.getAbsolutePath()
//                                  + QDir::separator()
//                                  + "spatial0");
    
    AString errorMessage;
        
    if ( ! errorMessage.isEmpty()) {
        throw DataFileException(errorMessage);
    }
    
    const AString filename(fileInfo.getAbsoluteFilePath());
    QFile jsonfile(filename);
    if ( ! jsonfile.open(QIODevice::ReadOnly)) {
        throw DataFileException("Error opening "
                                + filename
                                + ": "
                                + jsonfile.errorString());
    }
    
    const bool printJsonFlag(false);
    QByteArray dataRead(jsonfile.readAll());
    QString s(dataRead);
    if (printJsonFlag) {
        std::cout << "-->" << s << "<---" << std::endl;
    }
    QJsonParseError jsonError;
    QJsonDocument json = QJsonDocument::fromJson(dataRead,
                                                 &jsonError);
    if (jsonError.error != QJsonParseError::NoError) {
        throw DataFileException("Failed to read JSON from "
                                + filename
                                + " with error: "
                                + jsonError.errorString()
                                + " at offset: "
                                + QString::number(jsonError.offset));
    }
    
    const bool prettyPrintFlag(true);
    if (prettyPrintFlag) {
        AString nameOut(FileInformation::assembleFileComponents(fileInfo.getAbsolutePath(),
                                                                "formatted",
                                                                "json"));
        QByteArray jsonOut(json.toJson(QJsonDocument::JsonFormat::Indented));
        QFile fileOut(nameOut);
        if (fileOut.open(QIODevice::WriteOnly)) {
            fileOut.write(jsonOut);
            fileOut.close();
        }
        else {
            throw DataFileException("Error opening " + nameOut
                                    + ": " + fileOut.errorString());
        }
    }
    
    if ( ! json.isObject()) {
        throw DataFileException("Top level JSON in "
                                + filename
                                + " is not a JsonObject");
    }

    try {
        readNeuroglancerJson(fileInfo,
                                 json.object());
        
    }
    catch (const DataFileException& dfe) {
        throw DataFileException("While reading "
                                + filename
                                + ": "
                                + dfe.whatString());
    }
}

/**
 * Read the Neuroglancer JSON
 * @param topObject
 *    The top-level JSON object
 * @throw DataFileException
 */
void
NeuroglancerAnnotationsFile::readNeuroglancerJson(const FileInformation& /*fileInfo*/,
                                                  const QJsonObject& root)
{
    AString errorMessage;
    
    const AString rootTypeName = root.value("@type").toString();
    if (rootTypeName != "neuroglancer_annotations_v1") {
        errorMessage.appendWithNewLine("@type="
                                       + rootTypeName
                                       + "but should be: neuroglancer_annotations_v1");
    }
    const QString annTypeName(root.value("annotation_type").toString().toUpper());
    if (annTypeName == "POINT") {
        m_annotationType = NeuroglancerAnnotationTypeEnum::POINT;
    }
    else if (annTypeName == "LINE") {
        m_annotationType = NeuroglancerAnnotationTypeEnum::LINE;
    }
    else if (annTypeName == "AXIS_ALIGNED_BOUNDING_BOX") {
        m_annotationType = NeuroglancerAnnotationTypeEnum::AXIS_ALIGNED_BOUNDING_BOX;
    }
    else if (annTypeName == "ELLIPSOID") {
        m_annotationType = NeuroglancerAnnotationTypeEnum::ELLIPSOID;
    }
    else if (annTypeName == "POLYLINE") {
        m_annotationType = NeuroglancerAnnotationTypeEnum::POLYLINE;
    }
    else {
        errorMessage.appendWithNewLine("Unrecognized 'annotation_type'="
                                       + annTypeName);
    }
    if (m_annotationType != NeuroglancerAnnotationTypeEnum::POINT) {
        errorMessage.appendWithNewLine("annotation_type="
                                       + annTypeName
                                       + " not supported.");
    }
    
    const AString byIdDirName(root.value("by_id").toObject().value("key").toString());
    if (byIdDirName.isEmpty()) {
        errorMessage.appendWithNewLine("by_id is missing or empty.");
    }
    else {
        m_byIdDirectoryName = (m_infoFileDirectoryName
                         + QDir::separator()
                         + byIdDirName);
        if ( ! QDir(byIdDirName).exists()) {
            errorMessage.appendWithNewLine("by_id directory does not exist: "
                                           + m_byIdDirectoryName);
        }
    }

    readDimensions(root.value("dimensions").toObject());
    
    m_lowerBound = readFloatArray(root.value("lower_bound").toArray());
    m_upperBound = readFloatArray(root.value("upper_bound").toArray());

    readProperties(root.value("properties").toArray());
    readSpatial(root.value("spatial").toArray());
}

/**
 * Read a float array into a float vector
 * @param array
 *   The json array
 * @return
 *    A float vector
 */
std::vector<float>
NeuroglancerAnnotationsFile::readFloatArray(const QJsonArray &array)
{
    std::vector<float> arrayOut;
    arrayOut.reserve(array.size());
    for (const QJsonValue& v : array) {
        arrayOut.push_back(v.toDouble());
    }
    return arrayOut;
}

/**
 * Read a int array into a int vector
 * @param array
 *   The json array
 * @return
 *    A int vector
 */
std::vector<int32_t>
NeuroglancerAnnotationsFile::readIntArray(const QJsonArray &array)
{
    std::vector<int32_t> arrayOut;
    arrayOut.reserve(array.size());
    for (const QJsonValue& v : array) {
        arrayOut.push_back(v.toInt());
    }
    return arrayOut;
}

/**
 * Read a dimension object
 * @param dimsObj
 *   The dimensions object
 */
void
NeuroglancerAnnotationsFile::readDimensions(const QJsonObject &dimsObj)
{
    for (auto it = dimsObj.constBegin(); it != dimsObj.constEnd(); ++it) {
        const QJsonArray pair = it.value().toArray();
        const AString dimName(it.key().toLower());
        Axis axis(Axis::X);
        if (dimName == "x") {
            axis = Axis::X;
        }
        else if (dimName == "y") {
            axis = Axis::Y;
        }
        else if (dimName == "z") {
            axis = Axis::Z;
        }
        else {
            throw DataFileException("Unrecogized dimension="
                                    + it.key());
        }
        
        float resolution(0.0);
        Unit unit(Unit::UNITLESS);
        if (pair.size() >= 1) {
            resolution = pair.at(0).toDouble();
        }
        float unitScale = 1.0;
        if (pair.size() >= 2) {
            const QString unitName(pair.at(1).toString().toLower());
            if (unitName == "m") {
                unit = Unit::MILLIMETERS;
                unitScale = 1000;
            }
            else if (unitName == "cm") {
                unit = Unit::MILLIMETERS;
                unitScale = 100;
            }
            else if (unitName == "mm") {
                unit = Unit::MILLIMETERS;
                unitScale = 1.0;
            }
            else if (unitName == "um") {
                unit = Unit::MILLIMETERS;
                unitScale = 0.001;
            }
            else if (unitName == "nm") {
                unit = Unit::MILLIMETERS;
                unitScale = 0.000001;
            }
            else if (unitName == "s") {
                unit = Unit::SECONDS;
            }
            else if (unitName.isEmpty()) {
                unit = Unit::UNITLESS;
            }
            else {
                throw DataFileException("Unsupported unit="
                                        + pair.at(1).toString());
            }
            
            switch (unit) {
                case Unit::MILLIMETERS:
                    break;
                case Unit::SECONDS:
                    throw DataFileException("Seconds not supported for unit");
                    break;
                case Unit::UNITLESS:
                    throw DataFileException("Unitless not supported for unit");
                    break;
            }
        }
        
        Dimension* d(NULL);
        switch (axis) {
            case Axis::X:
                d = &m_xDimension;
                d->m_axis = Axis::X;
                break;
            case Axis::Y:
                d = &m_yDimension;
                d->m_axis = Axis::Y;
                break;
            case Axis::Z:
                d = &m_zDimension;
                d->m_axis = Axis::Z;
                break;
        }
        d->m_units      = unit;
        d->m_unitScale  = unitScale;
        d->m_resolution = resolution;
        d->m_valid      = true;
    }
}

/**
 * Read a properties array
 * @param propsArray
 *    The properties array
 */
void
NeuroglancerAnnotationsFile::readProperties(const QJsonArray &propsArr)
{
    /*
     * m_lowerBound.size() == 3 for XYZ
     */
    int64_t offset(sizeof(float) * m_lowerBound.size());
    switch (m_annotationType) {
        case NeuroglancerAnnotationTypeEnum::INVALID:
            CaretAssert(0);
            break;
        case NeuroglancerAnnotationTypeEnum::AXIS_ALIGNED_BOUNDING_BOX:
            /* Two XYZ */
            offset *= 2;
            break;
        case NeuroglancerAnnotationTypeEnum::ELLIPSOID:
            /* Center XYZ + XYZ-Radius */
            offset *= 2;
            break;
        case NeuroglancerAnnotationTypeEnum::LINE:
            /* Two XYZ Endpoints */
            offset *= 2;
            break;
        case NeuroglancerAnnotationTypeEnum::POINT:
            /* One XYZ */
            offset *= 1;
            break;
        case NeuroglancerAnnotationTypeEnum::POLYLINE:
            offset *= 2;
            break;
    }
    
    for (const QJsonValue &pv : propsArr) {
        const QJsonObject po = pv.toObject();
        
        const AString id(po.value("id").toString());
        const AString description(po.value("description").toString());
        const AString typeName(po.value("type").toString().toLower());

        DataType dataType(DataType::INVALID);
        int32_t dataTypeSize(0);
        if (typeName == "rgb") {
            dataType = DataType::RGB;
            dataTypeSize = 3;
        }
        else if (typeName == "rgba") {
            dataType = DataType::RGBA;
            dataTypeSize = 4;
        }
        else if (typeName == "uint8") {
            dataType = DataType::UINT8;
            dataTypeSize = 1;
        }
        else if (typeName == "int8") {
            dataType = DataType::INT8;
            dataTypeSize = 1;
        }
        else if (typeName == "uint16") {
            dataType = DataType::UINT16;
            dataTypeSize = 2;
        }
        else if (typeName == "int16") {
            dataType = DataType::INT16;
            dataTypeSize = 2;
        }
        else if (typeName == "uint32") {
            dataType = DataType::UINT32;
            dataTypeSize = 4;
        }
        else if (typeName == "int32") {
            dataType = DataType::INT32;
            dataTypeSize = 4;
        }
        else if (typeName == "float32") {
            dataType = DataType::FLOAT32;
            dataTypeSize = 4;
        }
        else {
            throw DataFileException("Unknown type=" + typeName);
        }
        CaretAssert(dataType != DataType::INVALID);
        
        std::vector<AString> enumLabels;
        if (po.contains("enum_labels")) {
            for (const QJsonValue &lv : po.value("enum_labels").toArray())
                enumLabels.push_back(lv.toString());
        }
        
        std::vector<int32_t> enumValues;
        if (po.contains("enum_values")) {
            enumValues = readIntArray(po.value("enum_values").toArray());
        }
        
        Property property;
        property.m_propertyType = dataType;
        property.m_description = description;
        property.m_id = id;
        property.m_fileOffset = offset;

        if ( ! enumLabels.empty()) {
            if (enumLabels.size() == enumValues.size()) {
                const int32_t numItems(enumLabels.size());
                for (int32_t i = 0; i < numItems; i++) {
                    property.m_enumValueLabel.insert(std::make_pair(enumValues[i],
                                                                    enumLabels[i]));
                }
            }
            else {
                throw DataFileException("Number of enum values="
                                        + AString::number(enumValues.size())
                                        + " and enum labels="
                                        + AString::number(enumLabels.size())
                                        + " do not match for property: "
                                        + description);
            }
        }

        m_properties.push_back(property);

        offset += dataTypeSize;
    }
}

/**
 * Read a spatial array
 * @param spatialArr
 *   The spatial array
 * @return
 *   The spatial grid into
 */
std::vector<NeuroglancerAnnotationsFile::SpatialGrid>
NeuroglancerAnnotationsFile::readSpatial(const QJsonArray &spatialArr)
{
    std::vector<SpatialGrid> grids;
    grids.reserve(spatialArr.size());
    
    for (const QJsonValue &sv : spatialArr) {
        const QJsonObject so = sv.toObject();
        
        SpatialGrid g;
        g.m_path = so.value("key").toString();
        g.m_chunkSize = readIntArray(so.value("chunk_size").toArray());
        g.m_gridShape = readIntArray(so.value("grid_shape").toArray());
        g.m_limit = so.value("limit").toInt();
        
        grids.push_back(g);
    }
    return grids;
}

/**
 * Write the data file.
 *
 * @param filename
 *    Name of the data file.
 * @throws DataFileException
 *    If the file was not successfully written.
 */
void
NeuroglancerAnnotationsFile::writeFile(const AString& /*filename*/)
{
    throw DataFileException("Writing of Neuroglancer File is not supported.");
}

/**
 * Save subclass data to the scene.
 *
 * @param sceneAttributes
 *    Attributes for the scene.  Scenes may be of different types
 *    (full, generic, etc) and the attributes should be checked when
 *    restoring the scene.
 *
 * @param sceneClass
 *     sceneClass to which data members should be added.  Will always
 *     be valid (non-NULL).
 */
void
NeuroglancerAnnotationsFile::saveFileDataToScene(const SceneAttributes* sceneAttributes,
                                            SceneClass* sceneClass)
{
    CaretDataFile::saveFileDataToScene(sceneAttributes,
                                       sceneClass);
    m_sceneAssistant->saveMembers(sceneAttributes,
                                  sceneClass);
}

/**
 * Restore file data from the scene.
 *
 * @param sceneAttributes
 *    Attributes for the scene.  Scenes may be of different types
 *    (full, generic, etc) and the attributes should be checked when
 *    restoring the scene.
 *
 * @param sceneClass
 *     sceneClass for the instance of a class that implements
 *     this interface.  Will NEVER be NULL.
 */
void
NeuroglancerAnnotationsFile::restoreFileDataFromScene(const SceneAttributes* sceneAttributes,
                                                 const SceneClass* sceneClass)
{
    CaretDataFile::restoreFileDataFromScene(sceneAttributes,
                                            sceneClass);
    m_sceneAssistant->restoreMembers(sceneAttributes,
                                     sceneClass);
}

/**
 * Convert a dimension to a string representation
 * @param dimension
 *    The dimension
 * @return
 *    String describing dimension
 */
AString
NeuroglancerAnnotationsFile::dimensionToString(const Dimension& dimension)
{
    AString axisText;
    switch (dimension.m_axis) {
        case Axis::X:
            axisText = "X";
            break;
        case Axis::Y:
            axisText = "Y";
            break;
        case Axis::Z:
            axisText = "Z";
            break;
    }
    
    AString unitText;
    switch (dimension.m_units) {
        case Unit::MILLIMETERS:
            unitText = "Millimeters";
            break;
        case Unit::SECONDS:
            unitText = "Seconds";
            break;
        case Unit::UNITLESS:
            unitText = "Unitless";
            break;
    }
    AString s("Axis=" + axisText
              + ", Unit=" + unitText
              + ", UnitScale=" + AString::number(dimension.m_unitScale)
              + ", Resolution=" + AString::number(dimension.m_resolution));
    
    return s;
}

/**
 * Convert an annotation type to a string representation
 * @param annotationType
 *    The annotation type
 * @return
 *    String describing data type
 */
AString
NeuroglancerAnnotationsFile::annotationFileTypeToString(const AnnotationFileType& annotationFileType)
{
    AString annTypeName("Invalid");
    switch (annotationFileType) {
        case AnnotationFileType::AXIS_ALIGNED_BOUNDING_BOX:
            annTypeName = "Axis Aligned Bounding Box";
            break;
        case AnnotationFileType::ELLIPSOID:
            annTypeName = "Ellipsoid";
            break;
        case AnnotationFileType::LINE:
            annTypeName = "Line";
            break;
        case AnnotationFileType::POINT:
            annTypeName = "Point";
            break;
        case AnnotationFileType::POLYLINE:
            annTypeName = "Polyline";
            break;
    }
    return annTypeName;
}

/**
 * Convert a data type to a string representation
 * @param dataType
 *    The data type
 * @return
 *    String describing data type
 */
AString
NeuroglancerAnnotationsFile::dataTypeToString(const DataType& dataType)
{
    AString dataTypeName;
    switch (dataType) {
        case DataType::INVALID:
            dataTypeName = "Invalid";
            break;
        case DataType::RGB:
            dataTypeName = "RGB";
            break;
        case DataType::RGBA:
            dataTypeName = "RGBA";
            break;
        case DataType::UINT8:
            dataTypeName = "UINT8";
            break;
        case DataType::INT8:
            dataTypeName = "INT8";
            break;
        case DataType::UINT16:
            dataTypeName = "UINT16";
            break;
        case DataType::INT16:
            dataTypeName = "INT16";
            break;
        case DataType::UINT32:
            dataTypeName = "UINT32";
            break;
        case DataType::INT32:
            dataTypeName = "INT32";
            break;
        case DataType::FLOAT32:
            dataTypeName = "FLOAT32";
            break;
    }
    
    return dataTypeName;
}

/**
 * Read the data files in the 'byId" directory
 */
void
NeuroglancerAnnotationsFile::readNeuroglancerAnnotationFiles()
{
    QDir dir(m_byIdDirectoryName);
    if ( ! dir.exists()) {
        throw DataFileException("byID directory does not exist: "
                                + m_byIdDirectoryName);
    }
    
    const QStringList filenamesList(dir.entryList(QDir::Files));
    QStringListIterator iter(filenamesList);
    std::vector<AString> annFileNames(filenamesList.begin(),
                                      filenamesList.end());
    AStringNaturalComparison::sortStringVector(annFileNames);
    
    float xScale(1.0);
    float yScale(1.0);
    float zScale(1.0);
    if (m_xDimension.m_valid) {
        xScale = m_xDimension.m_unitScale * m_xDimension.m_resolution;
        CaretAssert(xScale != 0.0);
    }
    if (m_yDimension.m_valid) {
        yScale = m_yDimension.m_unitScale * m_yDimension.m_resolution;
        CaretAssert(yScale != 0.0);
    }
    if (m_zDimension.m_valid) {
        zScale = m_zDimension.m_unitScale * m_zDimension.m_resolution;
        CaretAssert(zScale != 0.0);
    }

    for (const AString& filenameOnly : annFileNames) {
        const AString pathAndName(m_byIdDirectoryName
                                  + QDir::separator()
                                  + filenameOnly);
        QFile file(pathAndName);
        if ( ! file.open(QFile::ReadOnly)) {
            throw DataFileException("Failed to read file "
                                    + pathAndName);
        }
        
        /*
         * Neuorglancer files are LITTLE ENDIAN Single Precision
         */
        QDataStream dataStream(&file);
        dataStream.setByteOrder(QDataStream::LittleEndian);
        dataStream.setFloatingPointPrecision(QDataStream::SinglePrecision);
        
        QList<QStandardItem*> annotationProperties;
        std::vector<const NeuroglancerAnnotationPropertyValue*> neuroAnnProperties;
        
        float annotationSize(2.0);
        QColor annotationColor(255, 255, 255, 255);
        
        float i, j, k;
        dataStream >> i >> j >> k;
        
        const int32_t numProperties(m_properties.size());
        for (int32_t iProp = 0; iProp < numProperties; iProp++) {
            CaretAssertVectorIndex(m_properties, iProp);
            const Property& property(m_properties[iProp]);
            
            const int64_t offset(property.m_fileOffset);
            CaretAssert(offset > 0);
            
            NeuroglancerAnnotationPropertyDataTypeEnum::Enum propertyType(NeuroglancerAnnotationPropertyDataTypeEnum::INVALID);
            QVariant propertyValue = "InvalidSeekFailed";
            AString propertyLabelText;
            if (file.seek(offset)) {
                switch (property.m_propertyType) {
                    case DataType::INVALID:
                        propertyType = NeuroglancerAnnotationPropertyDataTypeEnum::INVALID;
                        propertyValue = "InvalidDataType";
                        break;
                    case DataType::RGB:
                    {
                        uint8_t r, g, b;
                        dataStream >> r >> g >> b;
                        QColor color(r, g, b);
                        propertyValue = QVariant::fromValue(color);
                        propertyType = NeuroglancerAnnotationPropertyDataTypeEnum::RGBA;
                        
                        annotationColor.setRgb(r, g, b);
                    }
                        break;
                    case DataType::RGBA:
                    {
                        uint8_t r, g, b, a;
                        dataStream >> r >> g >> b >> a;
                        QColor color(r, g, b, a);
                        propertyValue = QVariant::fromValue(color);
                        propertyType = NeuroglancerAnnotationPropertyDataTypeEnum::RGBA;

                        annotationColor.setRgb(r, g, b, a);
                    }
                        break;
                    case DataType::UINT8:
                    {
                        uint8_t v;
                        dataStream >> v;
                        propertyValue = static_cast<uint32_t>(v);
                        propertyType = NeuroglancerAnnotationPropertyDataTypeEnum::UNSIGNED_INTEGER;
                    }
                        break;
                    case DataType::INT8:
                    {
                        int8_t v;
                        dataStream >> v;
                        propertyValue = static_cast<int32_t>(v);
                        propertyType = NeuroglancerAnnotationPropertyDataTypeEnum::INTEGER;
                    }
                        break;
                    case DataType::UINT16:
                    {
                        uint16_t v;
                        dataStream >> v;
                        propertyValue = static_cast<uint32_t>(v);
                        propertyType = NeuroglancerAnnotationPropertyDataTypeEnum::UNSIGNED_INTEGER;
                    }
                        break;
                    case DataType::INT16:
                    {
                        int16_t v;
                        dataStream >> v;
                        propertyValue = static_cast<int32_t>(v);
                        propertyType = NeuroglancerAnnotationPropertyDataTypeEnum::INTEGER;
                    }
                        break;
                    case DataType::UINT32:
                    {
                        int32_t v;
                        dataStream >> v;
                        propertyValue = v;
                        propertyType = NeuroglancerAnnotationPropertyDataTypeEnum::UNSIGNED_INTEGER;
                    }
                        break;
                    case DataType::INT32:
                    {
                        uint32_t v;
                        dataStream >> v;
                        propertyValue = v;
                        propertyType = NeuroglancerAnnotationPropertyDataTypeEnum::INTEGER;
                    }
                        break;
                    case DataType::FLOAT32:
                    {
                        float v;
                        dataStream >> v;
                        propertyValue = v;
                        propertyType = NeuroglancerAnnotationPropertyDataTypeEnum::FLOAT;
                    }
                        break;
                }
                
                if (property.m_enumValueLabel.empty()) {
                    if (property.m_description == "size") {
                        annotationSize = propertyValue.toFloat();
                    }
                }
                else {
                    int32_t labelIndex(-1);
                    switch (propertyType) {
                        case NeuroglancerAnnotationPropertyDataTypeEnum::INVALID:
                            break;
                        case NeuroglancerAnnotationPropertyDataTypeEnum::RGBA:
                            break;
                        case NeuroglancerAnnotationPropertyDataTypeEnum::UNSIGNED_INTEGER:
                            labelIndex = static_cast<int32_t>(propertyValue.toUInt());
                            break;
                        case NeuroglancerAnnotationPropertyDataTypeEnum::INTEGER:
                            labelIndex = propertyValue.toInt();
                            break;
                        case NeuroglancerAnnotationPropertyDataTypeEnum::FLOAT:
                            break;
                        case NeuroglancerAnnotationPropertyDataTypeEnum::LABEL:
                            break;
                    }

                    if (labelIndex >= 0) {
                        auto labelIter(property.m_enumValueLabel.find(labelIndex));
                        if (labelIter != property.m_enumValueLabel.end()) {
                            propertyLabelText = labelIter->second;
                            propertyType = NeuroglancerAnnotationPropertyDataTypeEnum::LABEL;
                        }
                    }
                }
            }
            
            NeuroglancerAnnotationPropertyValue* neuroAnnProp(new NeuroglancerAnnotationPropertyValue(property.m_description,
                                                                                            propertyType,
                                                                                            propertyValue,
                                                                                            propertyLabelText));
            annotationProperties.push_back(neuroAnnProp);
            neuroAnnProperties.push_back(neuroAnnProp);
        }
        
        bool supportedFlag(false);
        switch (m_annotationType) {
            case NeuroglancerAnnotationTypeEnum::INVALID:
                break;
            case NeuroglancerAnnotationTypeEnum::AXIS_ALIGNED_BOUNDING_BOX:
                break;
            case NeuroglancerAnnotationTypeEnum::ELLIPSOID:
                break;
            case NeuroglancerAnnotationTypeEnum::LINE:
                break;
            case NeuroglancerAnnotationTypeEnum::POINT:
                supportedFlag = true;
                break;
            case NeuroglancerAnnotationTypeEnum::POLYLINE:
                break;
        }
        if ( ! supportedFlag) {
            throw DataFileException("Neuroglancer Annotation type not supported for "
                                    + NeuroglancerAnnotationTypeEnum::toGuiName(m_annotationType));
        }
        
        std::vector<Vector3D> ijks { Vector3D(i, j, k) };
        
        NeuroglancerAnnotation* na = new NeuroglancerAnnotation(m_annotationType,
                                                                filenameOnly,
                                                                ijks,
                                                                annotationColor,
                                                                annotationSize,
                                                                neuroAnnProperties);
        
        QList<QStandardItem*> newRow;
        newRow.push_back(na);
        newRow.append(annotationProperties);
        
        m_model->appendRow(newRow);
    }
    
    if (m_model->columnCount() > 0) {
        QStringList headerLabels;
        headerLabels << "Annotation";
        for (const auto& p : m_properties) {
            headerLabels << p.m_description;
        }
        m_model->setHorizontalHeaderLabels(headerLabels);
    }
}

/**
 * @return Number of annotations
 */
int32_t
NeuroglancerAnnotationsFile::getNumberOfAnnotations() const
{
    return m_model->rowCount();
}

/**
 * @return Annotation at the given index
 * @param index
 *    Index of annotation
 */
NeuroglancerAnnotation*
NeuroglancerAnnotationsFile::getAnnotation(const int32_t index)
{
    CaretAssert((index >= 0)
                && (index < m_model->rowCount()));
    QStandardItem* item(m_model->item(index));
    CaretAssert(item);
    NeuroglancerAnnotation* neuroAnn(dynamic_cast<NeuroglancerAnnotation*>(item));
    CaretAssert(neuroAnn);
    return neuroAnn;
}

/**
 * @return Annotation at the given index (const method)
 * @param index
 *    Index of annotation
 */
const NeuroglancerAnnotation*
NeuroglancerAnnotationsFile::getAnnotation(const int32_t index) const
{
    CaretAssert((index >= 0)
                && (index < m_model->rowCount()));
    QStandardItem* item(m_model->item(index));
    CaretAssert(item);
    NeuroglancerAnnotation* neuroAnn(dynamic_cast<NeuroglancerAnnotation*>(item));
    CaretAssert(neuroAnn);
    return neuroAnn;
}

/**
 * @return XYZ of an annotation coordinate
 * @param annotationIndex
 *    Index of the annotation
 * @param coordinateIndex
 *    Index of the annotation's coordinate
 */
Vector3D
NeuroglancerAnnotationsFile::getAnnotationCoordinateXYZ(const int32_t annotationIndex,
                                                        const int32_t coordinateIndex) const
{
    const NeuroglancerAnnotation* ann(getAnnotation(annotationIndex));
    CaretAssert(ann);
    
    Vector3D ijk(ann->getIJK(coordinateIndex));
    Vector3D xyz(ijk);
    const CaretDataFile* cdf(m_volumeFileSelectionModel->getSelectedFile());
    if (cdf != NULL) {
        const VolumeFile* volumeFile(cdf->castToVolumeFile());
        if (volumeFile != NULL) {
            volumeFile->indexToSpace(ijk, xyz);
        }
    }
    
    return xyz;
}

/**
 * @return The model containing the annotations
 */
QStandardItemModel*
NeuroglancerAnnotationsFile::getModel()
{
    return m_model.get();
}

/**
 * @return The model containing the annotations
 */
const QStandardItemModel*
NeuroglancerAnnotationsFile::getModel() const
{
    return m_model.get();
}



