
/*LICENSE_START*/
/*
 *  Copyright (C) 2026 Washington University School of Medicine
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */
/*LICENSE_END*/

#define __NEUROGLANCER_PINS_FILE_DECLARE__
#include "NeuroglancerAnnotationsFile.h"
#undef __NEUROGLANCER_PINS_FILE_DECLARE__

#include <cmath>

#include <zlib.h>

#include <QDataStream>
#include <QDir>
#include <QFile>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonValue>
#include <QStandardItemModel>

#include "AStringNaturalComparison.h"
#include "CaretAssert.h"
#include "CaretDataFileSelectionModel.h"
#include "CaretLogger.h"
#include "DataCompressZLib.h"
#include "DataFileException.h"
#include "DataFileContentInformation.h"
#include "EventManager.h"
#include "FileInformation.h"
#include "GiftiMetaData.h"
#include "NeuroglancerAnnotation.h"
#include "NeuroglancerAnnotationLabel.h"
#include "NeuroglancerAnnotationLabelModel.h"
#include "NeuroglancerAnnotationModel.h"
#include "NeuroglancerAnnotationPropertyValue.h"
#include "SceneClass.h"
#include "SceneClassAssistant.h"
#include "VolumeFile.h"

using namespace caret;


    
/**
 * \class caret::NeuroglancerAnnotationsFile 
 * \brief Neuroglancer pins file
 * \ingroup Files
 *
 * https://github.com/google/neuroglancer/blob/master/src/datasource/precomputed/annotations.md
 *
 * JSON reading code initially generated by Claude.
 */

/**
 * Constructor.
 */
NeuroglancerAnnotationsFile::NeuroglancerAnnotationsFile()
: CaretDataFile(DataFileTypeEnum::NEUROGLANCER_ANNOTATION)
{
    m_fileMetaData.reset(new GiftiMetaData());
    m_sceneAssistant = std::unique_ptr<SceneClassAssistant>(new SceneClassAssistant());
    
    m_annotationModel.reset(new NeuroglancerAnnotationModel());
    
    m_volumeFileSelectionModel.reset(CaretDataFileSelectionModel::newInstanceForCaretDataFileTypes( { DataFileTypeEnum::VOLUME },
                                                                                                   { SubvolumeAttributes::VolumeType::ANATOMY } ));
    
    m_sceneAssistant->add("m_volumeFileSelectionModel",
                          "CaretDataFileSelectionModel",
                          m_volumeFileSelectionModel.get());
    
//    EventManager::get()->addEventListener(this, EventTypeEnum::);
}

/**
 * Destructor.
 */
NeuroglancerAnnotationsFile::~NeuroglancerAnnotationsFile()
{
    EventManager::get()->removeAllEventsFromListener(this);
}

/**
 * @return File casted to neuroglancer annotations file (avoids use of dynamic_cast that can be slow)
 * Overidden in NeuroglancerAnnotationsFile
 */
NeuroglancerAnnotationsFile*
NeuroglancerAnnotationsFile::castToNeuroglancerAnnotationsFile()
{
    return this;
}

/**
 * @return File casted to neuroglancer annotations file (avoids use of dynamic_cast that can be slow)
 * Overidden in NeuroglancerAnnotationsFile
 */
const NeuroglancerAnnotationsFile*
NeuroglancerAnnotationsFile::castToNeuroglancerAnnotationsFile() const
{
    return this;
}

/**
 * Receive an event.
 *
 * @param event
 *    An event for which this instance is listening.
 */
void
NeuroglancerAnnotationsFile::receiveEvent(Event* /*event*/)
{
//    if (event->getEventType() == EventTypeEnum::) {
//        <EVENT_CLASS_NAME*> eventName = dynamic_cast<EVENT_CLASS_NAME*>(event);
//        CaretAssert(eventName);
//
//        event->setEventProcessed();
//    }
}
 
/**
 * @return True if this file is empty
 */
bool
NeuroglancerAnnotationsFile::isEmpty() const
{
    return (m_annotationModel->rowCount() == 0);
}

/**
 * @return The structure for this file.
 */
StructureEnum::Enum
NeuroglancerAnnotationsFile::getStructure() const
{
    return StructureEnum::INVALID;
}

/**
 * Set the structure for this file.
 * @param structure
 *   New structure for this file.
 */
void
NeuroglancerAnnotationsFile::setStructure(const StructureEnum::Enum /*structure*/)
{
    /* structure not supported */
}

/**
 * @return Get access to the file's metadata.
 */
GiftiMetaData*
NeuroglancerAnnotationsFile::getFileMetaData()
{
    return m_fileMetaData.get();
}

/**
 * @return Get access to unmodifiable file's metadata.
 */
const GiftiMetaData*
NeuroglancerAnnotationsFile::getFileMetaData() const
{
    return m_fileMetaData.get();
}

/**
 * @return True if file supports file metadata, else false.
 */

bool
NeuroglancerAnnotationsFile::supportsFileMetaData() const
{
    return false;
}

/**
 * @return Selection model for volume that maps voxel indices to stereotaxic coordinates
 */
CaretDataFileSelectionModel*
NeuroglancerAnnotationsFile::getVolumeFileSelectionModel()
{
    return m_volumeFileSelectionModel.get();
}

/**
 * @return Selection model for volume that maps voxel indices to stereotaxic coordinates (const method)
 */
const CaretDataFileSelectionModel*
NeuroglancerAnnotationsFile::getVolumeFileSelectionModel() const
{
    return m_volumeFileSelectionModel.get();
}

/**
 * Add file info to data file content information
 * @param dataFileInformation
 *   The data file info structure
 */
void
NeuroglancerAnnotationsFile::addToDataFileContentInformation(DataFileContentInformation& dataFileInformation) const
{
    CaretDataFile::addToDataFileContentInformation(dataFileInformation);
    
    dataFileInformation.addNameAndValue("Info File Directory", m_infoFileDirectoryName);
    dataFileInformation.addNameAndValue("ByID Directory", m_byIdDirectoryName);
    addShardingToDataFileInformation(dataFileInformation, "By ID Sharding", m_byIdSharding);
    dataFileInformation.addNameAndValue("Dim X", dimensionToString(m_xDimension));
    dataFileInformation.addNameAndValue("Dim Y", dimensionToString(m_yDimension));
    dataFileInformation.addNameAndValue("Dim Z", dimensionToString(m_zDimension));

    const AString annTypeName(NeuroglancerAnnotationTypeEnum::toGuiName(m_annotationType));
    dataFileInformation.addNameAndValue("Annotation Type", annTypeName);
    dataFileInformation.addNameAndValue("Lower Bound", AString::fromNumbers(m_lowerBound));
    dataFileInformation.addNameAndValue("Upper Bound", AString::fromNumbers(m_upperBound));

    for (const Relationship& r : m_relationships) {
        dataFileInformation.addNameAndValue("Relationships ID", r.m_id);
        dataFileInformation.addNameAndValue("Relationships Directory", r.m_directoryName);
        addShardingToDataFileInformation(dataFileInformation, "Relationships Sharding", r.m_sharding);
    }
    
    for (const Property& p : m_properties) {
        dataFileInformation.addNameAndValue("Property ID", p.m_id);
        dataFileInformation.addNameAndValue("   Description", p.m_description);
        dataFileInformation.addNameAndValue("   Property Type", dataTypeToString(p.m_propertyType));
        dataFileInformation.addNameAndValue("   Offset", p.m_fileOffset);
        
        if ( ! p.m_enumValueLabel.empty()) {
            for (const auto& mapInfo : p.m_enumValueLabel) {
                dataFileInformation.addNameAndValue("   ", (AString::number(mapInfo.first)
                                                            + " " + mapInfo.second));
            }
        }
        /*
         DataType m_propertyType = DataType::INVALID;
         AString m_description;
         AString m_id;
         std::map<int32_t, AString> m_enumValueLabel;
         int64_t m_fileOffset = -1;

         */
    }
    
    const int32_t numRows(m_annotationModel->rowCount());
    dataFileInformation.addNameAndValue("Number of annotations", AString::number(numRows));
    const int32_t numCols(m_annotationModel->columnCount());
    for (int32_t iRow = 0; iRow < numRows; iRow++) {
        for (int32_t jCol = 0; jCol < numCols; jCol++) {
            const QStandardItem* item(m_annotationModel->item(iRow, jCol));
            const NeuroglancerAnnotationBase* nab(dynamic_cast<const NeuroglancerAnnotationBase*>(item));
            if (nab != NULL) {
                const AString indent((jCol == 0)
                                     ? AString::number(iRow)
                                     : "   ");
                dataFileInformation.addNameAndValue(indent,
                                                    nab->toString());
            }
        }
    }
}

/**
 * Add description of sharding to data file information
 * @param shardingName
 *    Name of the sharding
 * @param sharding
 *    The sharding instance
 */
void
NeuroglancerAnnotationsFile::addShardingToDataFileInformation(DataFileContentInformation& dataFileInformation,
                                                              const AString& shardingName,
                                                              const Sharding& sharding) const
{
    dataFileInformation.addNameAndValue("Sharding Name", shardingName);
    if (sharding.m_validFlag) {
        dataFileInformation.addNameAndValue("  Sharding Type", sharding.m_type);
        dataFileInformation.addNameAndValue("  Sharding Data Encoding", sharding.m_dataEncoding);
        dataFileInformation.addNameAndValue("  Sharding Hash", sharding.m_hash);
        dataFileInformation.addNameAndValue("  Sharding Minishard Bits", sharding.m_minishardBits);
        dataFileInformation.addNameAndValue("  Sharding Minishard Index Encoding", sharding.m_minishardIndexEncoding);
        dataFileInformation.addNameAndValue("  Sharding Preshift Bits", sharding.m_preshiftBits);
        dataFileInformation.addNameAndValue("  Sharding Shard Bits", sharding.m_shardBits);
    }
}
/**
 * @return True if file supports writing, else false.
 */
bool
NeuroglancerAnnotationsFile::supportsWriting() const
{
    return false;
}

/**
 * Read the data file.
 *
 * @param filename
 *    Name of the data file.
 * @throws DataFileException
 *    If the file was not successfully read.
 */
void
NeuroglancerAnnotationsFile::readFile(const AString& filename)
{
    clear();
    
    setFileName(filename);
    
    readNeuroglancerInfoFile(filename);
    
    for (const Relationship& r : m_relationships) {
        readNeuroglancerAnnotationShardedFiles(r.m_sharding,
                                               ShardingDataType::RELATIONSHIP,
                                               r.m_directoryName);
    }
    
    if (m_byIdSharding.m_validFlag) {
        /*
         * Multiple annotations are in one or more files
         */
        readNeuroglancerAnnotationShardedFiles(m_byIdSharding,
                                               ShardingDataType::ANNOTATION,
                                               m_byIdDirectoryName);
    }
    else {
        /*
         * Each annotation is in its own file
         */
        readNeuroglancerAnnotationFiles();
    }

    if (m_annotationModel->columnCount() > 0) {
        QStringList headerLabels;
        headerLabels << "Annotation";
        for (const auto& p : m_properties) {
            headerLabels << p.m_description;
        }
        m_annotationModel->setHeaderLabels(headerLabels);
    }
    
    clearModified();
}

/**
 * Read the neuroglancer "info" file.  The info file (in JSON) describes the contents of the other files.
 *
 * @param filenameIn
 *    Name of the data file.
 * @throws DataFileException
 *    If the file was not successfully read or other errors.
 */
void
NeuroglancerAnnotationsFile::readNeuroglancerInfoFile(const AString& filenameIn)
{
   FileInformation fileInfo(filenameIn);
    const AString nameNoPath(fileInfo.getFileName());
    if (nameNoPath != "info") {
        throw DataFileException("Name of file MUST be named \"info\" but is named \""
                                + nameNoPath + "\"");
    }
    
    m_infoFileDirectoryName = fileInfo.getAbsolutePath();
    
//    const AString spatial0DirName(fileInfo.getAbsolutePath()
//                                  + QDir::separator()
//                                  + "spatial0");
    
    AString errorMessage;
        
    if ( ! errorMessage.isEmpty()) {
        throw DataFileException(errorMessage);
    }
    
    /*
     * Open the "info" file
     */
    const AString filename(fileInfo.getAbsoluteFilePath());
    QFile jsonfile(filename);
    if ( ! jsonfile.open(QIODevice::ReadOnly)) {
        throw DataFileException("Error opening "
                                + filename
                                + ": "
                                + jsonfile.errorString());
    }
    
    /*
     * Read the entire "info" file
     */
    QByteArray dataRead(jsonfile.readAll());

    /*
     * Can print to help with debugging
     */
    const bool printJsonFlag(false);
    QString s(dataRead);
    if (printJsonFlag) {
        std::cout << "-->" << s << "<---" << std::endl;
    }
    
    /*
     * Allow Qt to parse the JSON text
     */
    QJsonParseError jsonError;
    QJsonDocument json = QJsonDocument::fromJson(dataRead,
                                                 &jsonError);
    if (jsonError.error != QJsonParseError::NoError) {
        throw DataFileException("Failed to read JSON from "
                                + filename
                                + " with error: "
                                + jsonError.errorString()
                                + " at offset: "
                                + QString::number(jsonError.offset));
    }
    
    /*
     * Can print a "pretty" (formatted with indentation
     * for easier reading) version of the JSON
     */
    const bool prettyPrintFlag(true);
    if (prettyPrintFlag) {
        AString nameOut(FileInformation::assembleFileComponents(fileInfo.getAbsolutePath(),
                                                                "formatted",
                                                                "json"));
        QByteArray jsonOut(json.toJson(QJsonDocument::JsonFormat::Indented));
        QFile fileOut(nameOut);
        if (fileOut.open(QIODevice::WriteOnly)) {
            fileOut.write(jsonOut);
            fileOut.close();
        }
        else {
            throw DataFileException("Error opening " + nameOut
                                    + ": " + fileOut.errorString());
        }
    }
    
    /*
     * Top level item must be a Json Object
     */
    if ( ! json.isObject()) {
        throw DataFileException("Top level JSON in "
                                + filename
                                + " is not a JsonObject");
    }

    try {
        parseNeuroglancerInfoFileJson(fileInfo,
                                      json.object());
        
    }
    catch (const DataFileException& dfe) {
        throw DataFileException("While reading "
                                + filename
                                + ": "
                                + dfe.whatString());
    }
}

/**
 * Parse the Neuroglancer Info file JSON
 * @param topObject
 *    The top-level JSON object
 * @throw DataFileException
 */
void
NeuroglancerAnnotationsFile::parseNeuroglancerInfoFileJson(const FileInformation& /*fileInfo*/,
                                                          const QJsonObject& root)
{
    AString errorMessage;
    
    const AString rootTypeName = root.value("@type").toString();
    if (rootTypeName != "neuroglancer_annotations_v1") {
        errorMessage.appendWithNewLine("@type="
                                       + rootTypeName
                                       + "but should be: neuroglancer_annotations_v1");
    }
    const QString annTypeName(root.value("annotation_type").toString().toUpper());
    if (annTypeName == "POINT") {
        m_annotationType = NeuroglancerAnnotationTypeEnum::POINT;
    }
    else if (annTypeName == "LINE") {
        m_annotationType = NeuroglancerAnnotationTypeEnum::LINE;
    }
    else if (annTypeName == "AXIS_ALIGNED_BOUNDING_BOX") {
        m_annotationType = NeuroglancerAnnotationTypeEnum::AXIS_ALIGNED_BOUNDING_BOX;
    }
    else if (annTypeName == "ELLIPSOID") {
        m_annotationType = NeuroglancerAnnotationTypeEnum::ELLIPSOID;
    }
    else if (annTypeName == "POLYLINE") {
        m_annotationType = NeuroglancerAnnotationTypeEnum::POLYLINE;
    }
    else {
        errorMessage.appendWithNewLine("Unrecognized 'annotation_type'="
                                       + annTypeName);
    }
    
    /*
     * We only support points
     */
    if (m_annotationType != NeuroglancerAnnotationTypeEnum::POINT) {
        errorMessage.appendWithNewLine("annotation_type="
                                       + annTypeName
                                       + " not supported.");
    }
    
    
    parseByIdObject(root.value("by_id").toObject());

    parseDimensionsObject(root.value("dimensions").toObject());
    
    m_lowerBound = parseFloatArray(root.value("lower_bound").toArray());
    m_upperBound = parseFloatArray(root.value("upper_bound").toArray());

    parsePropertiesArray(root.value("properties").toArray());
    parseSpatialArray(root.value("spatial").toArray());
    parseRelationshipsArray(root.value("relationships").toArray());
}

/**
 * Parse a float array into a float vector
 * @param array
 *   The json array
 * @return
 *    A float vector
 */
std::vector<float>
NeuroglancerAnnotationsFile::parseFloatArray(const QJsonArray &array)
{
    std::vector<float> arrayOut;
    arrayOut.reserve(array.size());
    for (const QJsonValue& v : array) {
        arrayOut.push_back(v.toDouble());
    }
    return arrayOut;
}

/**
 * Parse an int array into a int vector
 * @param array
 *   The json array
 * @return
 *    A int vector
 */
std::vector<int32_t>
NeuroglancerAnnotationsFile::parseIntArray(const QJsonArray &array)
{
    std::vector<int32_t> arrayOut;
    arrayOut.reserve(array.size());
    for (const QJsonValue& v : array) {
        arrayOut.push_back(v.toInt());
    }
    return arrayOut;
}

/**
 * Parse a dimension object
 * @param dimsObj
 *   The dimensions object
 */
void
NeuroglancerAnnotationsFile::parseDimensionsObject(const QJsonObject &dimsObj)
{
    for (auto it = dimsObj.constBegin(); it != dimsObj.constEnd(); ++it) {
        const QJsonArray pair = it.value().toArray();
        const AString dimName(it.key().toLower());
        Axis axis(Axis::X);
        if (dimName == "x") {
            axis = Axis::X;
        }
        else if (dimName == "y") {
            axis = Axis::Y;
        }
        else if (dimName == "z") {
            axis = Axis::Z;
        }
        else {
            throw DataFileException("Unrecogized dimension="
                                    + it.key());
        }
        
        float resolution(0.0);
        Unit unit(Unit::UNITLESS);
        if (pair.size() >= 1) {
            resolution = pair.at(0).toDouble();
        }
        float unitScale = 1.0;
        if (pair.size() >= 2) {
            const QString unitName(pair.at(1).toString().toLower());
            if (unitName == "m") {
                unit = Unit::MILLIMETERS;
                unitScale = 1000;
            }
            else if (unitName == "cm") {
                unit = Unit::MILLIMETERS;
                unitScale = 100;
            }
            else if (unitName == "mm") {
                unit = Unit::MILLIMETERS;
                unitScale = 1.0;
            }
            else if (unitName == "um") {
                unit = Unit::MILLIMETERS;
                unitScale = 0.001;
            }
            else if (unitName == "nm") {
                unit = Unit::MILLIMETERS;
                unitScale = 0.000001;
            }
            else if (unitName == "s") {
                unit = Unit::SECONDS;
            }
            else if (unitName.isEmpty()) {
                unit = Unit::UNITLESS;
            }
            else {
                throw DataFileException("Unsupported unit="
                                        + pair.at(1).toString());
            }
            
            switch (unit) {
                case Unit::MILLIMETERS:
                    break;
                case Unit::SECONDS:
                    throw DataFileException("Seconds not supported for unit");
                    break;
                case Unit::UNITLESS:
                    throw DataFileException("Unitless not supported for unit");
                    break;
            }
        }
        
        Dimension* d(NULL);
        switch (axis) {
            case Axis::X:
                d = &m_xDimension;
                d->m_axis = Axis::X;
                break;
            case Axis::Y:
                d = &m_yDimension;
                d->m_axis = Axis::Y;
                break;
            case Axis::Z:
                d = &m_zDimension;
                d->m_axis = Axis::Z;
                break;
        }
        d->m_units      = unit;
        d->m_unitScale  = unitScale;
        d->m_resolution = resolution;
        d->m_valid      = true;
    }
}

/**
 * Parse the "by_id" object
 * @param The by_id objectr
 */
void
NeuroglancerAnnotationsFile::parseByIdObject(const QJsonObject& byIdObject)
{
    const AString byIdDirName(byIdObject.value("key").toString());
    if (byIdDirName.isEmpty()) {
        throw DataFileException("by_id is missing or empty.");
    }
    else {
        m_byIdDirectoryName = (m_infoFileDirectoryName
                               + QDir::separator()
                               + byIdDirName);
        if ( ! QDir(m_byIdDirectoryName).exists()) {
            throw DataFileException("by_id directory does not exist: "
                                    + m_byIdDirectoryName);
        }
    }
    
    if (byIdObject.contains("sharding")) {
        const QJsonObject shardingObject(byIdObject.value("sharding").toObject());
        m_byIdSharding = parseShardingObject(shardingObject);
    }
}

/**
 * Parse a sharding object
 * @param shardingObject
 *    The JSON sharding object
 * @return
 *    Sharding class instance
 */
NeuroglancerAnnotationsFile::Sharding
NeuroglancerAnnotationsFile::parseShardingObject(const QJsonObject shardingObject)
{
    Sharding sharding;
    sharding.m_type = shardingObject.value("@type").toString();
    sharding.m_dataEncoding = shardingObject.value("data_encoding").toString();
    sharding.m_hash = shardingObject.value("hash").toString();
    sharding.m_minishardBits = shardingObject.value("minishard_bits").toInt();
    sharding.m_minishardIndexEncoding = shardingObject.value("minishard_index_encoding").toString();
    sharding.m_preshiftBits = shardingObject.value("preshift_bits").toInt();
    sharding.m_shardBits = shardingObject.value("shard_bits").toInt();
    
    sharding.m_validFlag = false;
    if (sharding.m_type.isNotEmpty()
        && sharding.m_dataEncoding.isNotEmpty()
        && sharding.m_hash.isNotEmpty()
        && (sharding.m_minishardBits >= 0)
        && sharding.m_minishardIndexEncoding.isNotEmpty()
        && (sharding.m_preshiftBits >= 0)
        && (sharding.m_shardBits >= 0)) {
        sharding.m_validFlag = true;
    }

    return sharding;
}

/**
 * Parse a relationships object
 * @param relationshipsArray
 *   The relationships array
 */
void
NeuroglancerAnnotationsFile::parseRelationshipsArray(const QJsonArray& relationshipsArray)
{
    const int32_t numElem(relationshipsArray.count());
    for (int32_t i = 0; i < numElem; i++) {
        Relationship relationship;
        const QJsonObject& relationshipsObject = relationshipsArray.at(i).toObject();
        const AString dirName(relationshipsObject.value("key").toString());
        if (dirName.isNotEmpty()) {
            relationship.m_directoryName = (m_infoFileDirectoryName
                                            + QDir::separator()
                                            + dirName);
            if ( ! QDir(relationship.m_directoryName).exists()) {
                throw DataFileException("relationships directory does not exist: "
                                        + relationship.m_directoryName);
            }
        }
        
        relationship.m_id = relationshipsObject.value("id").toString();
        
        if (relationshipsObject.contains("sharding")) {
            const QJsonObject shardingObject(relationshipsObject.value("sharding").toObject());
            relationship.m_sharding = parseShardingObject(shardingObject);
        }
        m_relationships.push_back(relationship);
    }
}


/**
 * Parse a properties array
 * @param propsArray
 *    The properties array
 */
void
NeuroglancerAnnotationsFile::parsePropertiesArray(const QJsonArray &propsArr)
{
    /*
     * m_lowerBound.size() == 3 for XYZ
     */
    int64_t offset(sizeof(float) * m_lowerBound.size());
    switch (m_annotationType) {
        case NeuroglancerAnnotationTypeEnum::INVALID:
            CaretAssert(0);
            break;
        case NeuroglancerAnnotationTypeEnum::AXIS_ALIGNED_BOUNDING_BOX:
            /* Two XYZ */
            offset *= 2;
            break;
        case NeuroglancerAnnotationTypeEnum::ELLIPSOID:
            /* Center XYZ + XYZ-Radius */
            offset *= 2;
            break;
        case NeuroglancerAnnotationTypeEnum::LINE:
            /* Two XYZ Endpoints */
            offset *= 2;
            break;
        case NeuroglancerAnnotationTypeEnum::POINT:
            /* One XYZ */
            offset *= 1;
            break;
        case NeuroglancerAnnotationTypeEnum::POLYLINE:
            offset *= 2;
            break;
    }
    
    for (const QJsonValue &pv : propsArr) {
        const QJsonObject po = pv.toObject();
        
        const AString id(po.value("id").toString());
        const AString description(po.value("description").toString());
        const AString typeName(po.value("type").toString().toLower());

        DataType dataType(DataType::INVALID);
        int32_t dataTypeSize(0);
        if (typeName == "rgb") {
            dataType = DataType::RGB;
            dataTypeSize = 3;
        }
        else if (typeName == "rgba") {
            dataType = DataType::RGBA;
            dataTypeSize = 4;
        }
        else if (typeName == "uint8") {
            dataType = DataType::UINT8;
            dataTypeSize = 1;
        }
        else if (typeName == "int8") {
            dataType = DataType::INT8;
            dataTypeSize = 1;
        }
        else if (typeName == "uint16") {
            dataType = DataType::UINT16;
            dataTypeSize = 2;
        }
        else if (typeName == "int16") {
            dataType = DataType::INT16;
            dataTypeSize = 2;
        }
        else if (typeName == "uint32") {
            dataType = DataType::UINT32;
            dataTypeSize = 4;
        }
        else if (typeName == "int32") {
            dataType = DataType::INT32;
            dataTypeSize = 4;
        }
        else if (typeName == "float32") {
            dataType = DataType::FLOAT32;
            dataTypeSize = 4;
        }
        else {
            throw DataFileException("Unknown type=" + typeName);
        }
        CaretAssert(dataType != DataType::INVALID);
        
        std::vector<AString> enumLabels;
        if (po.contains("enum_labels")) {
            for (const QJsonValue &lv : po.value("enum_labels").toArray())
                enumLabels.push_back(lv.toString());
        }
        
        std::vector<int32_t> enumValues;
        if (po.contains("enum_values")) {
            enumValues = parseIntArray(po.value("enum_values").toArray());
        }
        
        Property property;
        property.m_propertyType = dataType;
        property.m_description = description;
        property.m_id = id;
        property.m_fileOffset = offset;
        property.m_labelModel = NULL;

        if ( ! enumLabels.empty()) {
            if (enumLabels.size() == enumValues.size()) {
                NeuroglancerAnnotationLabelModel* labelModel(new NeuroglancerAnnotationLabelModel(description));
                const int32_t numItems(enumLabels.size());
                for (int32_t i = 0; i < numItems; i++) {
                    property.m_enumValueLabel.insert(std::make_pair(enumValues[i],
                                                                    enumLabels[i]));
                    NeuroglancerAnnotationLabel* label(new NeuroglancerAnnotationLabel(enumValues[i],
                                                                                       enumLabels[i]));
                    labelModel->addLabel(label);
                }
                m_labelModels.emplace_back(labelModel);
                property.m_labelModel = labelModel;
            }
            else {
                throw DataFileException("Number of enum values="
                                        + AString::number(enumValues.size())
                                        + " and enum labels="
                                        + AString::number(enumLabels.size())
                                        + " do not match for property: "
                                        + description);
            }
        }

        m_properties.push_back(property);

        offset += dataTypeSize;
    }
}

/**
 * Parse a spatial array
 * @param spatialArray
 *   The spatial array
 * @return
 *   The spatial grid into
 */
std::vector<NeuroglancerAnnotationsFile::SpatialGrid>
NeuroglancerAnnotationsFile::parseSpatialArray(const QJsonArray &spatialArray)
{
    std::vector<SpatialGrid> grids;
    grids.reserve(spatialArray.size());
    
    for (const QJsonValue &sv : spatialArray) {
        const QJsonObject so = sv.toObject();
        
        SpatialGrid g;
        g.m_path = so.value("key").toString();
        g.m_chunkSize = parseIntArray(so.value("chunk_size").toArray());
        g.m_gridShape = parseIntArray(so.value("grid_shape").toArray());
        g.m_limit = so.value("limit").toInt();
        
        grids.push_back(g);
    }
    return grids;
}

/**
 * Write the data file.
 *
 * @param filename
 *    Name of the data file.
 * @throws DataFileException
 *    If the file was not successfully written.
 */
void
NeuroglancerAnnotationsFile::writeFile(const AString& /*filename*/)
{
    throw DataFileException("Writing of Neuroglancer File is not supported.");
}

/**
 * Save subclass data to the scene.
 *
 * @param sceneAttributes
 *    Attributes for the scene.  Scenes may be of different types
 *    (full, generic, etc) and the attributes should be checked when
 *    restoring the scene.
 *
 * @param sceneClass
 *     sceneClass to which data members should be added.  Will always
 *     be valid (non-NULL).
 */
void
NeuroglancerAnnotationsFile::saveFileDataToScene(const SceneAttributes* sceneAttributes,
                                            SceneClass* sceneClass)
{
    CaretDataFile::saveFileDataToScene(sceneAttributes,
                                       sceneClass);
    m_sceneAssistant->saveMembers(sceneAttributes,
                                  sceneClass);
    SceneClass* annModelScene(m_annotationModel->saveToScene(sceneAttributes,
                                                             "m_annotationModel"));
    sceneClass->addClass(annModelScene);
    
    for (int32_t i = 0; i < getNumberOfLabelModels(); i++) {
        NeuroglancerAnnotationLabelModel* labelModel(getLabelModel(i));
        sceneClass->addClass(labelModel->saveToScene(sceneAttributes,
                                                     labelModel->getDescription()));
    }
}

/**
 * Restore file data from the scene.
 *
 * @param sceneAttributes
 *    Attributes for the scene.  Scenes may be of different types
 *    (full, generic, etc) and the attributes should be checked when
 *    restoring the scene.
 *
 * @param sceneClass
 *     sceneClass for the instance of a class that implements
 *     this interface.  Will NEVER be NULL.
 */
void
NeuroglancerAnnotationsFile::restoreFileDataFromScene(const SceneAttributes* sceneAttributes,
                                                 const SceneClass* sceneClass)
{
    CaretDataFile::restoreFileDataFromScene(sceneAttributes,
                                            sceneClass);
    m_sceneAssistant->restoreMembers(sceneAttributes,
                                     sceneClass);
    
    const SceneClass* annModelScene(sceneClass->getClass("m_annotationModel"));
    if (annModelScene != NULL) {
        m_annotationModel->restoreFromScene(sceneAttributes,
                                            annModelScene);
    }
    
    for (int32_t i = 0; i < getNumberOfLabelModels(); i++) {
        NeuroglancerAnnotationLabelModel* labelModel(getLabelModel(i));
        const SceneClass* labelClass(sceneClass->getClass(labelModel->getDescription()));
        if (labelClass != NULL) {
            labelModel->restoreFromScene(sceneAttributes, labelClass);
        }
    }
}

/**
 * Convert a dimension to a string representation
 * @param dimension
 *    The dimension
 * @return
 *    String describing dimension
 */
AString
NeuroglancerAnnotationsFile::dimensionToString(const Dimension& dimension)
{
    AString axisText;
    switch (dimension.m_axis) {
        case Axis::X:
            axisText = "X";
            break;
        case Axis::Y:
            axisText = "Y";
            break;
        case Axis::Z:
            axisText = "Z";
            break;
    }
    
    AString unitText;
    switch (dimension.m_units) {
        case Unit::MILLIMETERS:
            unitText = "Millimeters";
            break;
        case Unit::SECONDS:
            unitText = "Seconds";
            break;
        case Unit::UNITLESS:
            unitText = "Unitless";
            break;
    }
    AString s("Axis=" + axisText
              + ", Unit=" + unitText
              + ", UnitScale=" + AString::number(dimension.m_unitScale)
              + ", Resolution=" + AString::number(dimension.m_resolution));
    
    return s;
}

/**
 * Convert an annotation type to a string representation
 * @param annotationType
 *    The annotation type
 * @return
 *    String describing data type
 */
AString
NeuroglancerAnnotationsFile::annotationFileTypeToString(const AnnotationFileType& annotationFileType)
{
    AString annTypeName("Invalid");
    switch (annotationFileType) {
        case AnnotationFileType::AXIS_ALIGNED_BOUNDING_BOX:
            annTypeName = "Axis Aligned Bounding Box";
            break;
        case AnnotationFileType::ELLIPSOID:
            annTypeName = "Ellipsoid";
            break;
        case AnnotationFileType::LINE:
            annTypeName = "Line";
            break;
        case AnnotationFileType::POINT:
            annTypeName = "Point";
            break;
        case AnnotationFileType::POLYLINE:
            annTypeName = "Polyline";
            break;
    }
    return annTypeName;
}

/**
 * Convert a data type to a string representation
 * @param dataType
 *    The data type
 * @return
 *    String describing data type
 */
AString
NeuroglancerAnnotationsFile::dataTypeToString(const DataType& dataType)
{
    AString dataTypeName;
    switch (dataType) {
        case DataType::INVALID:
            dataTypeName = "Invalid";
            break;
        case DataType::RGB:
            dataTypeName = "RGB";
            break;
        case DataType::RGBA:
            dataTypeName = "RGBA";
            break;
        case DataType::UINT8:
            dataTypeName = "UINT8";
            break;
        case DataType::INT8:
            dataTypeName = "INT8";
            break;
        case DataType::UINT16:
            dataTypeName = "UINT16";
            break;
        case DataType::INT16:
            dataTypeName = "INT16";
            break;
        case DataType::UINT32:
            dataTypeName = "UINT32";
            break;
        case DataType::INT32:
            dataTypeName = "INT32";
            break;
        case DataType::FLOAT32:
            dataTypeName = "FLOAT32";
            break;
    }
    
    return dataTypeName;
}

/**
 * Read the data files in the 'byId" directory
 * Each file in the directory contains data for one annotation.
 */
void
NeuroglancerAnnotationsFile::readNeuroglancerAnnotationFiles()
{
    QDir dir(m_byIdDirectoryName);
    if ( ! dir.exists()) {
        throw DataFileException("byID directory does not exist: "
                                + m_byIdDirectoryName);
    }
    
    const QStringList filenamesList(dir.entryList(QDir::Files));
    QStringListIterator iter(filenamesList);
    std::vector<AString> annFileNames(filenamesList.begin(),
                                      filenamesList.end());
    AStringNaturalComparison::sortStringVector(annFileNames);
    
    float xScale(1.0);
    float yScale(1.0);
    float zScale(1.0);
    if (m_xDimension.m_valid) {
        xScale = m_xDimension.m_unitScale * m_xDimension.m_resolution;
        CaretAssert(xScale != 0.0);
    }
    if (m_yDimension.m_valid) {
        yScale = m_yDimension.m_unitScale * m_yDimension.m_resolution;
        CaretAssert(yScale != 0.0);
    }
    if (m_zDimension.m_valid) {
        zScale = m_zDimension.m_unitScale * m_zDimension.m_resolution;
        CaretAssert(zScale != 0.0);
    }

    for (const AString& filenameOnly : annFileNames) {
        const AString pathAndName(m_byIdDirectoryName
                                  + QDir::separator()
                                  + filenameOnly);
        QFile file(pathAndName);
        if ( ! file.open(QFile::ReadOnly)) {
            throw DataFileException("Failed to read file "
                                    + pathAndName);
        }
        
        /*
         * Use a datastream to read the file
         */
        QDataStream dataStream(&file);
        
        QByteArray emptyByteArray;
        readAnnotationFromDataStream(&file,
                                     emptyByteArray,
                                     dataStream,
                                     filenameOnly);
    }
}

/**
 * Read an annontation from a datastream
 * @param file
 *    File containing annotation.  If NULL, annotation is being read from in-memory data
 * @param dataBytes
 *    If 'file' is NULL, the annotation is being read from this byte array
 * @param dataStream
 *   The datastream
 * @param annotationID
 *    The annotation ID (may be filename when each annotation in its own file)
 */
void
NeuroglancerAnnotationsFile::readAnnotationFromDataStream(QFile* file,
                                                          const QByteArray& dataBytes,
                                                          QDataStream& dataStream,
                                                          const AString& annotationID)
{
    /*
     * Position/radii vectors, required by the annotation type, encoded as
     * float32le values:
     *
     *   - POINT:
     *       The position vector.
     *
     *   - LINE:
     *       The first endpoint position, followed by the second endpoint
     *       position.
     *
     *   - AXIS_ALIGNED_BOUNDING_BOX:
     *       The first position, followed by the second position.
     *
     *   - ELLIPSOID:
     *       The center position, followed by the radii vector.
     *
     *   - POLYLINE:
     *       The number of points as a uint32le value, followed by the
     *       position of each point as float32le.
     *
     * Properties, encoded per their type:
     *
     *   - uint32, int32, float32:
     *       Encoded as a little-endian value.
     *
     *   - uint16, int16:
     *       Encoded as a little-endian value.
     *
     *   - uint8, int8, rgb, rgba:
     *       Encoded as-is (no byte-order conversion needed).
     *
     * Padding:
     *   Up to 3 padding bytes (value 0) to align the next field to a
     *   4-byte offset.
     *
     * Below is ONLY when each annotation is in a single file (NOT sharded)
     *
     * Relationships, for each relationship specified in the info JSON file:
     *
     *   1. The number of object IDs, as a uint32le value.
     *   2. Each related object ID, as a uint64le value.
     */
    dataStream.setByteOrder(QDataStream::LittleEndian);
    dataStream.setFloatingPointPrecision(QDataStream::SinglePrecision);
    
    /*
     * The property values are added into same row as the annotation in the model
     */
    QList<QStandardItem*> modelRowPropertyValues;
    
    /*
     * The property values are also added to the annotation
     */
    std::vector<const NeuroglancerAnnotationPropertyValue*> neuroglancerAnnotationPropertyValues;
    
    float annotationSize(2.0);
    QColor annotationColor(255, 255, 255, 255);
    
    float i, j, k;
    dataStream >> i >> j >> k;
    
    const int32_t numProperties(m_properties.size());
    for (int32_t iProp = 0; iProp < numProperties; iProp++) {
        CaretAssertVectorIndex(m_properties, iProp);
        const Property& property(m_properties[iProp]);
        
        const int64_t offset(property.m_fileOffset);
        CaretAssert(offset > 0);
        
        NeuroglancerAnnotationPropertyDataTypeEnum::Enum propertyType(NeuroglancerAnnotationPropertyDataTypeEnum::INVALID);
        QVariant propertyValue = "InvalidSeekFailed";
        AString propertyLabelText;
            switch (property.m_propertyType) {
                case DataType::INVALID:
                    propertyType = NeuroglancerAnnotationPropertyDataTypeEnum::INVALID;
                    propertyValue = "InvalidDataType";
                    break;
                case DataType::RGB:
                {
                    uint8_t r, g, b;
                    dataStream >> r >> g >> b;
                    QColor color(r, g, b);
                    propertyValue = QVariant::fromValue(color);
                    propertyType = NeuroglancerAnnotationPropertyDataTypeEnum::RGBA;
                    
                    annotationColor.setRgb(r, g, b);
                }
                    break;
                case DataType::RGBA:
                {
                    uint8_t r, g, b, a;
                    dataStream >> r >> g >> b >> a;
                    QColor color(r, g, b, a);
                    propertyValue = QVariant::fromValue(color);
                    propertyType = NeuroglancerAnnotationPropertyDataTypeEnum::RGBA;
                    
                    annotationColor.setRgb(r, g, b, a);
                }
                    break;
                case DataType::UINT8:
                {
                    uint8_t v;
                    dataStream >> v;
                    propertyValue = static_cast<uint32_t>(v);
                    propertyType = NeuroglancerAnnotationPropertyDataTypeEnum::UNSIGNED_INTEGER;
                }
                    break;
                case DataType::INT8:
                {
                    int8_t v;
                    dataStream >> v;
                    propertyValue = static_cast<int32_t>(v);
                    propertyType = NeuroglancerAnnotationPropertyDataTypeEnum::INTEGER;
                }
                    break;
                case DataType::UINT16:
                {
                    uint16_t v;
                    dataStream >> v;
                    propertyValue = static_cast<uint32_t>(v);
                    propertyType = NeuroglancerAnnotationPropertyDataTypeEnum::UNSIGNED_INTEGER;
                }
                    break;
                case DataType::INT16:
                {
                    int16_t v;
                    dataStream >> v;
                    propertyValue = static_cast<int32_t>(v);
                    propertyType = NeuroglancerAnnotationPropertyDataTypeEnum::INTEGER;
                }
                    break;
                case DataType::UINT32:
                {
                    int32_t v;
                    dataStream >> v;
                    propertyValue = v;
                    propertyType = NeuroglancerAnnotationPropertyDataTypeEnum::UNSIGNED_INTEGER;
                }
                    break;
                case DataType::INT32:
                {
                    uint32_t v;
                    dataStream >> v;
                    propertyValue = v;
                    propertyType = NeuroglancerAnnotationPropertyDataTypeEnum::INTEGER;
                }
                    break;
                case DataType::FLOAT32:
                {
                    float v;
                    dataStream >> v;
                    propertyValue = v;
                    propertyType = NeuroglancerAnnotationPropertyDataTypeEnum::FLOAT;
                }
                    break;
            }
            
            if (property.m_enumValueLabel.empty()) {
                if (property.m_description == "size") {
                    annotationSize = propertyValue.toFloat();
                }
            }
            else {
                int32_t labelIndex(-1);
                switch (propertyType) {
                    case NeuroglancerAnnotationPropertyDataTypeEnum::INVALID:
                        break;
                    case NeuroglancerAnnotationPropertyDataTypeEnum::RGBA:
                        break;
                    case NeuroglancerAnnotationPropertyDataTypeEnum::UNSIGNED_INTEGER:
                        labelIndex = static_cast<int32_t>(propertyValue.toUInt());
                        break;
                    case NeuroglancerAnnotationPropertyDataTypeEnum::INTEGER:
                        labelIndex = propertyValue.toInt();
                        break;
                    case NeuroglancerAnnotationPropertyDataTypeEnum::FLOAT:
                        break;
                    case NeuroglancerAnnotationPropertyDataTypeEnum::LABEL:
                        break;
                }
                
                if (labelIndex >= 0) {
                    auto labelIter(property.m_enumValueLabel.find(labelIndex));
                    if (labelIter != property.m_enumValueLabel.end()) {
                        propertyLabelText = labelIter->second;
                        propertyType = NeuroglancerAnnotationPropertyDataTypeEnum::LABEL;
                    }
                }
            }
        
        NeuroglancerAnnotationPropertyValue* neuroAnnProp(new NeuroglancerAnnotationPropertyValue(property.m_description,
                                                                                                  propertyType,
                                                                                                  propertyValue,
                                                                                                  propertyLabelText,
                                                                                                  property.m_labelModel));
        modelRowPropertyValues.push_back(neuroAnnProp);
        neuroglancerAnnotationPropertyValues.push_back(neuroAnnProp);
    }

    QByteArray extraBytes;
    if (file != NULL) {
        /*
         * After reading the annotation, the file position must be at
         * a 4-byte offset (see comment at beginning of this function).
         */
        const int64_t bytesToSkip(file->pos() % 4);
        CaretAssert((bytesToSkip >= 0)
                    && (bytesToSkip <= 3));
        const int64_t bytesActuallySkipped(file->skip(bytesToSkip));
        if (bytesToSkip != bytesActuallySkipped) {
            CaretLogWarning("Failed to skip bytes at end of reading Neuroglancer Annotation");
        }
        
        if (m_debugFlag) {
            const int64_t bytesLeft(file->size() - file->pos());
            if (bytesLeft > 0) {
                /*
                 * Read the remaining bytes
                 */
                extraBytes.resize(bytesLeft);
                dataStream.readRawData(extraBytes.data(), bytesLeft);
            }
        }
    }
    else {
        /*
         * Read any remaining bytes
         */
        extraBytes.reserve(256);
        while (  ! dataStream.atEnd()) {
            char ch;
            dataStream >> ch;
            extraBytes.push_back(ch);
        }
        
        /*
         * There is no "pos()" in QDataStream so we need to determine
         * if we are at a 4-byte boundary and if there is "padding"
         */
        const int64_t dataArrayPos(dataBytes.length() - extraBytes.length());
        const int64_t remainder(dataArrayPos % 4);
        
        if (remainder >= 0) {
            /*
             * Skip over the padded bytes
             */
            if (remainder <= extraBytes.size()) {
                extraBytes = extraBytes.mid(remainder);
            }
            else {
                extraBytes.clear();
            }
        }
    }
    
    if ( ! extraBytes.isEmpty()) {
        if (m_debugFlag) std::cout << "Annotation: " << getFileName() << " has extra bytes at end, num="
        << extraBytes.size() << std::endl;
    }
    
    bool supportedFlag(false);
    switch (m_annotationType) {
        case NeuroglancerAnnotationTypeEnum::INVALID:
            break;
        case NeuroglancerAnnotationTypeEnum::AXIS_ALIGNED_BOUNDING_BOX:
            break;
        case NeuroglancerAnnotationTypeEnum::ELLIPSOID:
            break;
        case NeuroglancerAnnotationTypeEnum::LINE:
            break;
        case NeuroglancerAnnotationTypeEnum::POINT:
            supportedFlag = true;
            break;
        case NeuroglancerAnnotationTypeEnum::POLYLINE:
            break;
    }
    if ( ! supportedFlag) {
        throw DataFileException("Neuroglancer Annotation type not supported for "
                                + NeuroglancerAnnotationTypeEnum::toGuiName(m_annotationType));
    }
    
    std::vector<Vector3D> ijks { Vector3D(i, j, k) };
    
    /*
     * Create the annotation
     */
    NeuroglancerAnnotation* na = new NeuroglancerAnnotation(m_annotationType,
                                                            annotationID,
                                                            ijks,
                                                            annotationColor,
                                                            annotationSize,
                                                            neuroglancerAnnotationPropertyValues);
    
    /*
     * The annotation and properties must be inserted
     * as a row.  There does not appear to be a way
     * to add columns to a stadard item and keep them
     * in the same row.
     */
    QList<QStandardItem*> newRow;
    newRow.push_back(na);
    newRow.append(modelRowPropertyValues);
    
    m_annotationModel->addAnnotation(annotationID,
                                     newRow);
    
}


/**
 * Read the sharded data files for the given sharding data type
 * Sharded files contain one or more annotations in a single file.
 * @param shardingInfo
 *    The sharding info
 * @param shardingDataType
 *    Type of data stored in sharding
 * @param shardingDataDirectoryName
 *    Name of directory containing the sharded data
 */
void
NeuroglancerAnnotationsFile::readNeuroglancerAnnotationShardedFiles(const Sharding& shardingInfo,
                                                                    const ShardingDataType shardingDataType,
                                                                    const AString& shardingDataDirectoryName)
{
    QDir dir(shardingDataDirectoryName);
    if ( ! dir.exists()) {
        throw DataFileException("Read sharding directory does not exist: "
                                + shardingDataDirectoryName);
    }
    
    /*
     * For each shard number in the range [0, 2**shard_bits), there is a
     * <shard>.shard file, where <shard> is the lowercase base-16 shard number
     * zero padded to ceil(shard_bits/4) digits.
     */
    const int32_t numShardFiles(std::exp2(shardingInfo.m_shardBits));
    if (m_debugFlag) std::cout << "Num shard files: " << numShardFiles << std::endl;
    const int32_t numDigitsInFileName(std::ceil(shardingInfo.m_shardBits / 4));
    if (m_debugFlag)std::cout << "   Num digits in filename: " << numDigitsInFileName << std::endl;

    std::vector<AString> allShardFileNames;
    for (int32_t iFile = 0; iFile < numShardFiles; iFile++) {
        /*
         * Create filename from number with zero padding at beginning of filename
         * Filenames are in form "#.shard" where "#" is one or more digits
         * with leading zeros.
         */
        const AString filenameNumber(AString::number(iFile).rightJustified(numDigitsInFileName, '0'));
        const AString filenameOnly(filenameNumber + ".shard");
        const AString pathAndName(shardingDataDirectoryName
                                  + QDir::separator()
                                  + filenameOnly);
        allShardFileNames.push_back(pathAndName);
    }
    
    AStringNaturalComparison::sortStringVector(allShardFileNames);
    if (m_debugFlag)std::cout << "Sorted shard filenames" << std::endl;
    for (const AString& name : allShardFileNames) {
        if (m_debugFlag)std::cout << "   " << name << std::endl;
    }
    
    float xScale(1.0);
    float yScale(1.0);
    float zScale(1.0);
    if (m_xDimension.m_valid) {
        xScale = m_xDimension.m_unitScale * m_xDimension.m_resolution;
        CaretAssert(xScale != 0.0);
    }
    if (m_yDimension.m_valid) {
        yScale = m_yDimension.m_unitScale * m_yDimension.m_resolution;
        CaretAssert(yScale != 0.0);
    }
    if (m_zDimension.m_valid) {
        zScale = m_zDimension.m_unitScale * m_zDimension.m_resolution;
        CaretAssert(zScale != 0.0);
    }
    
    for (const AString& shardFileName : allShardFileNames) {
        if (m_debugFlag) std::cout << "Processing shareded annotations file: " << shardFileName << std::endl;
        
        QFile file(shardFileName);
        if ( ! file.open(QFile::ReadOnly)) {
            throw DataFileException("Failed to read file "
                                    + shardFileName);
        }
        if (m_debugFlag) std::cout << "File length: " << file.size() << std::endl;
        
        /*
         * Neuorglancer files are LITTLE ENDIAN Single Precision
         */
        QDataStream dataStream(&file);
        dataStream.setByteOrder(QDataStream::LittleEndian);
        dataStream.setFloatingPointPrecision(QDataStream::SinglePrecision);
        
        /*
         * From https://github.com/google/neuroglancer/blob/master/src/datasource/precomputed/sharded.md
         *
         * The first 2**minishard_bits * 16 bytes of each shard file is the
         * "shard index" consisting of 2**minishard_bits entries of the form:
         * - start_offset: uint64le, specifies the inclusive start byte offset
         *   of the "minishard index" in the shard file.
         * - end_offset: uint64le, specifies the exclusive end byte offset of the
         *   "minishard index" in the shard file.
         * Both the start_offset and end_offset are relative to the end of the
         * "shard index", i.e. shard_index_end = 2**minishard_bits * 16 bytes.
         *
         * That is, the encoded "minishard index" for a given minishard is stored
         * in the byte range [shard_index_end + start_offset, shard_index_end + end_offset)
         * of the shard file. A zero-length byte range indicates that there are no
         * chunk IDs in the minishard.
         */
        if (m_debugFlag) std::cout << "2**4: " << std::exp2(4.0) << std::endl;
        if (m_debugFlag) shardingInfo.print("By ID Sharding");
        const int64_t numEntries(std::exp2(shardingInfo.m_minishardBits));
        const int64_t shardIndexLength(numEntries * 16);
        const int64_t shardIndexEnd(shardIndexLength);
        if (m_debugFlag) std::cout << "   Num Entries: " << numEntries << std::endl;
        if (m_debugFlag) std::cout << "   Shard Index Length: " << shardIndexLength << std::endl;
        
        /*
         * Read the start and end offsets of the shards
         */
        std::vector<std::pair<uint64_t, uint64_t>> minishardStartOffsetAndLength;
        for (int64_t i = 0; i < numEntries; i++) {
            uint64_t startOffset, endOffset;
            dataStream >> startOffset >> endOffset;
            startOffset += shardIndexEnd;
            endOffset   += shardIndexEnd;
            const uint64_t minishardLength(endOffset - startOffset);
            if (m_debugFlag) std::cout << "   entry i: startOffset=" << std::hex << startOffset << ", endOffset=" << endOffset
            << std::dec << ", length=" << minishardLength << std::endl;
            if (minishardLength > 0) {
                minishardStartOffsetAndLength.push_back(std::make_pair(startOffset,
                                                                       minishardLength));
            }
        }
        
        /*
         * Read the minishards.  Must be done after reading start and
         * ending offset since reading minishard changes file read
         * position.
         */
        for (const auto& offsetAndLength : minishardStartOffsetAndLength) {
            const uint64_t startOffset(offsetAndLength.first);
            const uint64_t minishardLength(offsetAndLength.second);
            readEncodedMinishardIndex(file,
                                      shardingDataType,
                                      shardingInfo.m_dataEncoding,
                                      shardIndexEnd,
                                      shardingInfo.m_minishardIndexEncoding,
                                      startOffset,
                                      minishardLength);
        }
    }
}

/**
 * Read the encoded minishard index
 * @param file
 *    The QFile that is being read
 * @param shardingDataType
 *    The sharding data type
 * @param dataEncoding
 *    Type of encoding used to compress data
 * @param shardIndexEnd
 *    End of shard index
 * @param minishardIndexEncoding
 *    Encoding for the minishard indexing
 * @param minishardOffset
 *    The location of the minishard in the file
 * @param minishardLength
 *    Length of the minishard
 */
void
NeuroglancerAnnotationsFile::readEncodedMinishardIndex(QFile& file,
                                                       const ShardingDataType shardingDataType,
                                                       const AString& dataEncoding,
                                                       const uint64_t shardIndexEnd,
                                                       const AString& minishardIndexEncoding,
                                                       const uint64_t minishardOffset,
                                                       const uint64_t minishardLength)
{
    if (minishardLength <= 0) {
        return;
    }
    
    QByteArray uncompressedData;
    
    QByteArray compressedData;
    compressedData.resize(minishardLength);
    
    if (m_debugFlag) std::cout << "-------------------------------" << std::endl;
    if (m_debugFlag) std::cout << "Seeking to minishard offset: hex=" << std::hex << minishardOffset
       << ", dec=" << std::dec << minishardOffset<< std::endl;
    if (file.seek(minishardOffset)) {
        /*
         * Read the data (probably compressed)
         */
        const uint64_t numRead(file.read(compressedData.data(),
                                         minishardLength));
        if (numRead != minishardLength) {
            throw DataFileException("Failed to read "
                                    + AString::number(minishardLength)
                                    + " bytes.  Actually read"
                                    + AString::number(numRead)
                                    + " bytes from " + file.fileName());
        }
        
        /*
         * Decompress the minishard data
         */
        if ( ! decompressData(compressedData,
                              uncompressedData,
                              minishardIndexEncoding)) {
            return;
        }
        
        if (m_debugFlag) std::cout << "Length compressed=" << compressedData.length()
           << " uncompressed=" << uncompressedData.length() << std::endl;
        
        std::vector<ChunkInfo> minishardChunkInfo;
        processMinishardIndex(file,
                              shardingDataType,
                              shardIndexEnd,
                              uncompressedData,
                              dataEncoding,
                              minishardChunkInfo);
        
        readChunksFromShardFile(file,
                                shardingDataType,
                                dataEncoding,
                                minishardChunkInfo);
        
    }
    else {
        throw DataFileException("Failed to seek to "
                                + AString::number(minishardOffset)
                                + " in " + file.fileName());
    }
}

/**
 * Process a minishard
 * @param file
 *    The QFile that is being read
 * @param shardingDataType
 *    The sharding data type
 * @param shardIndexEnd
 *    End of shard index
 * @param minishardIndexData
 *    Data in the minishard index
 * @param dataEncoding
 *    Encoding of the chunk data
 * @param miniShardChunkInfoOut
 *    Output contains chunk info from the minishard index
 */
void
NeuroglancerAnnotationsFile::processMinishardIndex(QFile& file,
                                                   const ShardingDataType shardingDataType,
                                                   const uint64_t shardIndexEnd,
                                                   const QByteArray& minishardIndexData,
                                                   const AString& dataEncoding,
                                                   std::vector<ChunkInfo>& miniShardChunkInfoOut)
{
    /*
     * The "minishard index" stored in the shard file is encoded according to the
     * minishard_index_encoding metadata value. The decoded "minishard index" is a
     * binary string of 24*n bytes, specifying a contiguous C-order array of [3, n]
     * uint64le values. Values array[0, 0], ..., array[0, n-1] specify the chunk IDs
     * in the minishard, and are delta encoded, such that array[0, 0] is equal to the
     * ID of the first chunk, and the ID of chunk i is equal to the sum of
     * array[0, 0], ..., array[0, i]. The size of the data for chunk i is stored as
     * array[2, i]. Values array[1, 0], ..., array[1, n-1] specify the starting
     * offsets in the shard file of the data corresponding to each chunk, and are
     * also delta encoded relative to the end of the prior chunk, such that the
     * starting offset of the first chunk is equal to shard_index_end + array[1, 0],
     * and the starting offset of chunk i is the sum of
     * shard_index_end + array[1, 0], ..., array[1, i] and array[2, 0], ..., array[2, i-1].
     *
     * The start and size values in the minishard index specify the location in the
     * shard file of the chunk data, which is encoded according to the data_encoding
     * metadata value.
     */
    
    miniShardChunkInfoOut.clear();
    
    if (m_debugFlag) std::cout << "Minishard Index Data Length: " << minishardIndexData.length() << std::endl;
//    const std::ldiv_t divResult(std::ldiv(minishardIndexData.length(), 24));
//    if (m_debugFlag) std::cout << "   quot=" << divResult.quot << ", rem=" << divResult.rem << std::endl;
    
    QDataStream dataStream(minishardIndexData);
    dataStream.setByteOrder(QDataStream::LittleEndian);
    
//    if (m_debugFlag) {
//        const uint64_t len(std::min((qsizetype)128, minishardIndexData.length()));
//        const uint64_t* data64(reinterpret_cast<const uint64_t*>(minishardIndexData.data()));
//        for (uint64_t i = 0; i < len; i++) {
//            std:: cout << data64[i] << " ";
//        }
//        std::cout << std::endl;
//        return;
//    }
    const int64_t numChunks(minishardIndexData.length() / 24);
    const int64_t remainder(minishardIndexData.length() % 24);
    if (remainder != 0) {
        throw DataFileException("ERROR: minishard is not evenly divisible by 24, remainder="
                                + AString::number(remainder));
        return;
    }
    
    miniShardChunkInfoOut.resize(numChunks);
    
    /*
     * Row zero (dim i=0) contains chunk IDs
     * A chunkID is relative to the previous chunk ID
     */
    uint64_t previousChunkID(0);
    for (int64_t iChunk = 0; iChunk < numChunks; iChunk++) {
        if (dataStream.atEnd()) {
            throw DataFileException("End of stream at dim i=0 iChunk="
                                    + AString::number(iChunk));
        }
        uint64_t chunkID;
        dataStream >> chunkID;
        
        chunkID += previousChunkID;
        previousChunkID = chunkID;
        

        CaretAssertVectorIndex(miniShardChunkInfoOut, iChunk);
        miniShardChunkInfoOut[iChunk].m_id = chunkID;
    }
    
    /*
     * Row one (dim i=1) contains offsets that are
     * relative to the END of the previous chunk
     */
    for (int64_t iChunk = 0; iChunk < numChunks; iChunk++) {
        if (dataStream.atEnd()) {
            throw DataFileException("End of stream at dim i=1 iChunk="
                                    + AString::number(iChunk));
        }
        uint64_t chunkOffset;
        dataStream >> chunkOffset;
        miniShardChunkInfoOut[iChunk].m_relativeOffset = chunkOffset;
    }
    
    /*
     * Row two (dim i=2) contains sizes of the chunks
     */
    for (int64_t iChunk = 0; iChunk < numChunks; iChunk++) {
        if (dataStream.atEnd()) {
            throw DataFileException("End of stream at dim i=2 iChunk="
                                    + AString::number(iChunk));
        }
        uint64_t chunkSize;
        dataStream >> chunkSize;
        
        CaretAssertVectorIndex(miniShardChunkInfoOut, iChunk);
        miniShardChunkInfoOut[iChunk].m_size = chunkSize;
    }
    
    /*
     * Now that we have sizes we can compute offsets
     * to absolute positions in the file
     */
    int64_t previousChunkEndOffset(shardIndexEnd);
    for (int64_t iChunk = 0; iChunk < numChunks; iChunk++) {
        CaretAssertVectorIndex(miniShardChunkInfoOut, iChunk);
        ChunkInfo& ci(miniShardChunkInfoOut[iChunk]);
        ci.m_offset = previousChunkEndOffset + ci.m_relativeOffset;
        
        previousChunkEndOffset = ci.m_offset + ci.m_size;
    }
    
    if (m_debugFlag) {
        for (int64_t iChunk = 0; iChunk < numChunks; iChunk++) {
            CaretAssertVectorIndex(miniShardChunkInfoOut, iChunk);
            const ChunkInfo& ci(miniShardChunkInfoOut[iChunk]);
            if (m_debugFlag) std::cout << "Chunk " << iChunk
                << ": id=" << ci.m_id << ", offset=" << ci.m_offset
                << ", rel offset=" << ci.m_relativeOffset
                << ", size=" << ci.m_size << std::endl;;
        }
    }
}

/**
 * Read data (annotations) from the chunks from the shard file
 * @param file
 *    The QFile that is being read
 * @param shardingDataType
 *    The sharding data type
 * @param dataEncoding
 *    Encoding of the chunk data
 * @param miniShardChunkInfo
 *    Info about each chunk
 */
void
NeuroglancerAnnotationsFile::readChunksFromShardFile(QFile& file,
                                                     const ShardingDataType shardingDataType,
                                                     const AString& dataEncoding,
                                                     const std::vector<ChunkInfo>& miniShardChunkInfo)
{
    const int64_t numChunks(miniShardChunkInfo.size());
    for (int64_t i = 0; i < numChunks; i++) {
        CaretAssertVectorIndex(miniShardChunkInfo, i);
        const ChunkInfo& chunk(miniShardChunkInfo[i]);
        
        /*
         * Seek to the location of the chunk in the file.
         */
        if (file.seek(chunk.m_offset)) {
            QByteArray compressedData(file.read(chunk.m_size));
            
            QByteArray data;
            if ( ! decompressData(compressedData,
                                  data,
                                  dataEncoding)) {
                return;
            }
            
            /*
             * The chunk contains one annotation so read it
             */
            QDataStream dataStream(data);
            
            switch (shardingDataType) {
                case ShardingDataType::ANNOTATION:
                {
                    QFile* nullFile(NULL);
                    readAnnotationFromDataStream(nullFile,
                                                 data,
                                                 dataStream,
                                                 AString::number(chunk.m_id));
                }
                    break;
                case ShardingDataType::RELATIONSHIP:
                    readRelationshipsFromDataStream(data,
                                                    dataStream,
                                                    AString::number(chunk.m_id));
                    break;
            }
        }
        else {
            throw DataFileException("Failed to seek to "
            + AString::number(chunk.m_offset)
                                    + " for chunk "
                                    + AString::number(i));
        }
    }
}

/**
 * Decompress data using the given encoding name.
 * @param compressedDataIn
 *   The input compressed data
 * @param uncompressedDataOut
 *   The output uncompressed data if successful.
 * @param encodingName
 *   Name of the compression encoding
 * @return
 *   True if sucessful, else false.
 */
bool
NeuroglancerAnnotationsFile::decompressData(const QByteArray& compressedDataIn,
                                            QByteArray& uncompressedDataOut,
                                            const AString encodingName)
{
    if (encodingName == "gzip") {
        /*
         * Use GZIP decompression
         */
        if ( ! DataCompressZLib::uncompressData(compressedDataIn,
                                                uncompressedDataOut)) {
            throw DataFileException(" DataCompressZLib::gzipDecompress() failed");
        }
        return true;
    }
    else if ((encodingName == "raw")
             || encodingName.isEmpty()) {
        /*
         * No compression, output is simply input
         * Note: identical QByteArrays share data until one is changed
         * so no copying of data.
         */
        uncompressedDataOut = compressedDataIn;
        return true;
    }
    else {
        throw DataFileException("Unsupported encoding compression type="
                                + encodingName);
    }
    return false;
}

/**
 * Read a relationship from a datastream
 * @param data
 *    The data
 * @param dataStream
 *    The datastream wrapped around 'data'
 * @param relationshipID
 *    The relationship ID (may be filename when each annotation in its own file)
 */
void
NeuroglancerAnnotationsFile::readRelationshipsFromDataStream(const QByteArray& data,
                                                             QDataStream& dataStream,
                                                             const AString& relationshipID)
{
    dataStream.setByteOrder(QDataStream::LittleEndian);
    dataStream.setFloatingPointPrecision(QDataStream::SinglePrecision);
    
    uint64_t numAnn;
    dataStream >> numAnn;
    if (m_debugFlag) {
        std::cout << "Relation ID=" << relationshipID
        << ", length=" << data.length()
        << ", num ann= " << numAnn << std::endl;
    }
 }

/**
 * @return XYZ of an annotation's coordinate
 * @param annotation
 *    The annotations
 * @param coordinateIndex
 *    Index of the annotation's coordinate
 */
Vector3D
NeuroglancerAnnotationsFile::annotationIJKtoXYZ(const NeuroglancerAnnotation* annotation,
                                                const int32_t coordinateIndex) const
{
    Vector3D xyz(0.0, 0.0, 0.0);
    
    CaretAssert(annotation);
    if (annotation != NULL) {
        Vector3D ijk(annotation->getIJK(coordinateIndex));
        xyz = ijk;
        const CaretDataFile* cdf(m_volumeFileSelectionModel->getSelectedFile());
        if (cdf != NULL) {
            const VolumeFile* volumeFile(cdf->castToVolumeFile());
            if (volumeFile != NULL) {
                volumeFile->indexToSpace(ijk, xyz);
            }
        }
    }
    
    return xyz;
}

/**
 * @return The model containing the annotations
 */
NeuroglancerAnnotationModel*
NeuroglancerAnnotationsFile::getAnnotationModel()
{
    return m_annotationModel.get();
}

/**
 * @return The model containing the annotations
 */
const NeuroglancerAnnotationModel*
NeuroglancerAnnotationsFile::getAnnotationModel() const
{
    return m_annotationModel.get();
}

/**
 * @return Number of label models
 */
int32_t
NeuroglancerAnnotationsFile::getNumberOfLabelModels() const
{
    return m_labelModels.size();
}

/**
 * @return Label model at the given index
 * @param index
 *   Index of the label model
 */
NeuroglancerAnnotationLabelModel*
NeuroglancerAnnotationsFile::getLabelModel(const int32_t index)
{
    CaretAssertVectorIndex(m_labelModels, index);
    return m_labelModels[index].get();
}

/**
 * @return Label model at the given index (const method)
 * @param index
 *   Index of the label model
 */
const NeuroglancerAnnotationLabelModel*
NeuroglancerAnnotationsFile::getLabelModel(const int32_t index) const
{
    CaretAssertVectorIndex(m_labelModels, index);
    return m_labelModels[index].get();
}

/* =========================================================== */

/**
 * Print the sharding information
 * @param name
 *    Name of sharding
 */
void
NeuroglancerAnnotationsFile::Sharding::print(const AString& name) const
{
    std::cout << "Sharding " << name << std::endl;
    std::cout << "  m_type:" << m_type << std::endl;
    std::cout << "  m_dataEncoding:" << m_dataEncoding << std::endl;
    std::cout << "  m_hash:" << m_hash << std::endl;
    std::cout << "  m_minishardBits:" << m_minishardBits << std::endl;
    std::cout << "  m_minishardIndexEncoding:" << m_minishardIndexEncoding << std::endl;
    std::cout << "  m_preshiftBits:" << m_preshiftBits << std::endl;
    std::cout << "  m_shardBits:" << m_shardBits << std::endl;
    std::cout << "  m_validFlag:" << AString::fromBool(m_validFlag) << std::endl;
}
